### ISSUE TITLE
Python meep frequency domain solver example error

### ISSUE THREAD

**Issue by amrit-poudel** [NanoComp/meep#311] opened 2018-05-01 03:17 UTC
I was able to build meep-1.4.3 from source without any error. All test passed (both C++ and python)
I tried simple examples in python. All works fine. Then I went ahead to try frequency domain solver and tried running the following code:
http://meep.readthedocs.io/en/master/Python_Tutorials/Frequency_Domain_Solver/
to generate the figure therein, but I kept running into the following error:

-----------
Meep: using complex fields.
on time step 1881 (time=94.05), 0.00212682 s/step
residual[95] = 0.00469916
on time step 3763 (time=188.15), 0.00212589 s/step
residual[190] = 0.000298668
final residual = 3.32244e-09
Finished solve_cw after 4961 steps and 248 CG iters.
Traceback (most recent call last):
  File "/home/Amrit/PycharmProjects/MEEP/ring_resonator_fdfd_fdtd.py", line 40, in <module>
    ez_dat[:, :, i] = sim.get_array(center=mp.Vector3(), size=mp.Vector3(sxy-2*dpml, sxy-2*dpml), component=mp.Ez)
  File "/home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep/simulation.py", line 896, in get_array
    self.fields.get_array_slice_dimensions(v, dim_sizes)
  File "/home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep/__init__.py", line 2725, in get_array_slice_dimensions
    return _meep.fields_get_array_slice_dimensions(self, where, dims, data)
NotImplementedError: Wrong number or type of arguments for overloaded function 'fields_get_array_slice_dimensions'.
  Possible C/C++ prototypes are:
    meep::fields::get_array_slice_dimensions(meep::volume const &,int [3],void *)
    meep::fields::get_array_slice_dimensions(meep::volume const &,int [3])

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Another error I encountered running time domain version of the same code:

Traceback (most recent call last):
  File "/home/Amrit/PycharmProjects/MEEP/ring_resonator_fdfd_fdtd.py", line 83, in <module>
    dfts = sim.add_dft_fields([mp.Ez], mp.Volume(center=mp.Vector3(), size=mp.Vector3(sxy-2*dpml,sxy-2*dpml)), fcen, fcen, 1)
  File "/home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep/simulation.py", line 698, in add_dft_fields
    return self.fields.add_dft_fields(components, where, freq_min, freq_max, nfreq)
  File "/home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep/__init__.py", line 2562, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, fields, name)
  File "/home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep/__init__.py", line 50, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'fields' object has no attribute 'add_dft_fields'

**Comment by amrit-poudel** [comment] 2018-05-02 05:37
I added solve_cw() function from the github simulation.py  to simulation.py file located under /lib/python/site-packages/meep of meep v1.4.3 and I no longer get error related to get_array_slice_dimensions or solve_cw.

However, the second error--AttributeError: 'fields' object has no attribute 'add_dft_fields'-- still exists.

I think this is a bug that can be easily fixed, but I do not know and/or do not have time to find out which file to edit.

**Comment by ChristopherHogan** [comment] 2018-05-02 13:37
Hi. There was an issue with the documentation not being in sync with the API. I've fixed this in #313. However, that is separate from the issue you are experiencing. I am unable to reproduce the errors you see, but it looks like python is importing an older version of meep instead of the one you just built. I would try the following:

```bash
rm -rf /home/Amrit/HPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages/meep
./configure --prefix=/home/Amrit/HPC_LIB/MEEP_MPI_TEST (etc.)
make
make check
make install
export PYTHONPATH=/home/AmritHPC_LIB/MEEP_MPI_TEST/lib/python2.7/site-packages
```
You probably have to set `PYTHONPATH` from inside PyCharm.

**Comment by ChristopherHogan** [comment] 2018-05-02 13:39
Also, you mentioned that you built Meep 1.4.3. If you mean you downloaded the 1.4.3 release tarball, then it does not include the features in the frequency domain solver example. You have to build from the head of the master branch.

**Comment by amrit-poudel** [comment] 2018-05-02 15:27
could you please confirm whether add_dft_fields and get_array_slice_dimensions work if I build meep from the head of the master branch?  Are you able to run both time and frequency domains test cases from the link I mentioned above?
I tried building from the head before (before I tried 1.4.3), but I kept encountering the same error as above.

**Comment by ChristopherHogan** [comment] 2018-05-02 15:56
> could you please confirm whether add_dft_fields and get_array_slice_dimensions work if I build meep from the head of the master branch?
Yes, I just confirmed that they work with the latest master. 

> Are you able to run both time and frequency domains test cases from the link I mentioned above?
Yes, after the changes in #313.

**Comment by ChristopherHogan** [comment] 2018-05-02 15:57
You could try running the example from the command line in case pycharm is interfering somehow.

**Comment by amrit-poudel** [comment] 2018-05-03 15:53
I tried building meep 1.4.3 (tarball) and meep from the master branch and compare the two.  I can build meep 1.4.3 with all tests passed on my linux machine. However,I encounter the following error messages during "make" from master branch:
meep_wrap.cxx:16463: error: ‘h5file_extending’ is not a member of ‘meep’
meep_wrap.cxx:16463: error: ‘arg1’ was not declared in this scope
meep_wrap.cxx:16463: error: ‘h5file_extending’ is not a member of ‘meep’
meep_wrap.cxx:16463: error: expected primary-expression before ‘)’ token
meep_wrap.cxx:16463: error: expected ‘;’ before numeric constant
meep_wrap.cxx:16469: error: ‘h5file_extending’ is not a member of ‘meep’
meep_wrap.cxx:16469: error: expected primary-expression before ‘)’ token
meep_wrap.cxx:16469: error: expected ‘;’ before ‘SWIG_Guile_MustGetPtr’
meep_wrap.cxx: In function ‘scm_unused_struct* _wrap_h5file_extending_dindex_get(scm_unused_struct*)’:
meep_wrap.cxx:16487: error: ‘h5file_extending’ is not a member of ‘meep’
.........
.........

If I proceed further with "make check", then the following tests failed:
2D_convergence

It does not get to python test.

I would think that building meep from master branch would be similar, if not identical, to building v 1.4.3. Am I missing something? Please note that I have followed all the instructions for building meep from the source, else I would not have been able to build and test v 1.4.3 successfully from the source in the first place.

**Comment by ChristopherHogan** [comment] 2018-05-03 16:11
What's the output of `$ swig -version`?

> I would think that building meep from master branch would be similar, if not identical, to building v 1.4.3.

The release tarball (v1.4.3) has already run `autogen.sh` which generates configure, and it has run SWIG to create the scheme and python .cpp wrapper files. When building from github, these steps are done on the user side, so the process is a little different. The instructions [here](http://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source) detail the process of building from Github. 

Can you include some commands demonstrating how you're building from the Github source?

**Comment by amrit-poudel** [comment] 2018-05-04 06:14
Here is how I build from the source on a linux machine. Works  just fine with meep v1.4.3 (have done it this way since meep was first released). All the required binaries and shared libraries (specified below) are in the PATH and LD_LIBRARY_PATH.


cd meep-master

export LIBS="-lopenblas"

export HARMINV_LIBS="-L/home/Amrit/HPC_LIB/HARMINV/lib"
export HARMINV_CFLAGS="-I/home/Amrit/HPC_LIB/HARMINV/include"

export CPPFLAGS="-I/home/Amrit/HPC_LIB/GSL/include -I/home/Amrit/HPC_LIB/FFTW_MPI/include -I/home/Amrit/HPC_LIB/HDF5_MPI/include -I/home/Amrit/HPC_LIB/HARMINV/include -I/home/Amrit/HPC_LIB/OPENBLAS/include -I/home/Amrit/HPC_LIB/LIBCTL/include -I/home/Amrit/HPC_LIB/GUILE/include -I/home/Amrit/HPC_LIB/MPB/include"

export LDFLAGS="-L/home/Amrit/HPC_LIB/GSL/lib -L/home/Amrit/HPC_LIB/FFTW_MPI/lib -L/home/Amrit/HPC_LIB/HDF5_MPI/lib -L/home/Amrit/HPC_LIB/HARMINV/lib -L/home/Amrit/HPC_LIB/OPENBLAS/lib -L/home/Amrit/HPC_LIB/LIBCTL/lib -L/home/Amrit/HPC_LIB/GUILE/lib -L/home/Amrit/HPC_LIB/MPB/lib"

./autogen.sh --prefix=/home/Amrit/HPC_LIB/MEEP_MPI_TEST "CC=mpicc" "CXX=mpic++" --enable-shared --with-mpi --with-blas=/home/Amrit/HPC_LIB/OPENBLAS/lib/libopenblas.so --with-lapack=/home/Amrit/HPC_LIB/OPENBLAS/lib/libopenblas.so --with-hdf5 --with-libctl=/home/Amrit/HPC_LIB/LIBCTL/share/libctl PYTHON=python2



This gives me error I mentioned above when building from the master branch.


swig version I currently have on the machine is:
SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

**Comment by ChristopherHogan** [comment] 2018-05-04 15:37
That looks reasonable. What error is 2D_convergence failing with? Can you `cat` the `tests/test-suite.log` file? It's strange that the libmeep test is failing, since the build is failing only for the scheme interface. If you only need the python interface, you can try:
```bash
pushd src && make && popd
pushd libmeepgeom && make && popd
pushd libpympb && make && popd
pushd python && make && popd
```
instead of running the top-level `make`.

**Comment by amrit-poudel** [comment] 2018-05-04 16:07
Here is the output in tests/test-suite.log file. This is all I have in this log file.

====================================
   meep 1.5: tests/test-suite.log
====================================

1 of 19 tests failed.

.. contents:: :depth: 2


FAIL: 2D_convergence (exit: 1)
==============================

Using MPI version 3.1, 2 processes
Running holes square-lattice resolution convergence test.
Checking convergence for ey field...
(The correct frequency should be 0.179944.)
frequency for a=30 is 0.179632, 0.179749 (shifted), 0.17969 (mean)
Unshifted freq error is -0.281165/30/30
Shifted freq error is -0.175337/30/30
Frequency difference with a of 30 is -0.105828/30/30
frequency for a=25 is 0.17963, 0.179856 (shifted), 0.179743 (mean)
Unshifted freq error is -0.196313/25/25
Shifted freq error is -0.0551143/25/25
Frequency difference with a of 25 is -0.141199/25/25
frequency for a=20 is 0.179822, 0.180153 (shifted), 0.179988 (mean)
Unshifted freq error is -0.048724/20/20
Shifted freq error is 0.0837453/20/20
Frequency difference with a of 20 is -0.132469/20/20
meep: Frequency doesn't converge properly with a.
frequency for a=15 is 0.180183, 0 (shifted), 0.0900916 (mean)
Unshifted freq error is 0.0538094/15/15
Shifted freq error is -40.4874/15/15
meep: Frequency doesn't converge properly with a.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
"test-suite.log" 43L, 1819C

**Comment by amrit-poudel** [comment] 2018-05-04 16:42
I am interested in python interface only. I suppose python interface can do everything that scheme or C++ interface can. 

How to I test meep, if I make using:
pushd src && make && popd
pushd libmeepgeom && make && popd
pushd libpympb && make && popd
pushd python && make && popd


Do I need to run individual make check instead of top level "make check" ?

Could you please let me know how I can do that? Thanks for your help.

**Comment by ChristopherHogan** [comment] 2018-05-04 18:05
You can run `make check` in each subfolder that has tests:
```bash
pushd tests && make check && popd
pushd libmeepgeom && make check && popd
pushd python && make check && popd
```

**Comment by ChristopherHogan** [comment] 2018-05-04 20:49
Since only the tests that import `h5py` fail, I assume your installation of `h5py` is linked with a different version than the version you built meep with. Since the missing symbol is related to MPI, the h5py in HPC_LIB/H5PY is probably linking with serial hdf5 while meep is linking with parallel. You can try running `ldd` on some of the .so files in in HPC_LIB/H5PY/lib/python2.7/site-packages/h5py to verify. Did you install h5py with the `HDF5_MPI="ON"` option?

**Comment by amrit-poudel** [comment] 2018-05-04 21:04
I just checked and confirmed that h5py is linked to parallel hdf5. Serial version is not even in the path. If this were the source of error, I am surprised that I do not see this occurring with 1.4.3 build. I can build meep v 1.4.3 without any issues and all tests pass. The only reason I am interested in master branch is  to test:
http://meep.readthedocs.io/en/master/Python_Tutorials/Frequency_Domain_Solver/

**Comment by ChristopherHogan** [comment] 2018-05-07 13:58
The line
```python
dfts = sim.add_dft_fields([mp.Ez], mp.Volume(center=mp.Vector3(), size=mp.Vector3(sxy - 2dpml,sxy - 2dpml)), fcen, fcen, 1)
```
in the error output suggests that you're using the code from before PR #313 was merged. You'll notice that the latest version at http://meep.readthedocs.io/en/master/Python_Tutorials/Frequency_Domain_Solver/ calls `add_dft_fields` like this: `add_dft_fields([mp.Ez], fcen, fcen, 1, where=where)`, with the volume as a keyword argument instead of positional. Please try the latest version.

**Comment by amrit-poudel** [comment] 2018-05-07 15:06
Have these changes been pushed to the master branch? I downloaded the zipped master branch on Friday but still got that error. I will try later today again. Thanks for your help.

**Comment by ChristopherHogan** [comment] 2018-05-07 15:17
Yes, you can see the changes on master [here](https://github.com/stevengj/meep/blob/master/doc/docs/Python_Tutorials/Frequency_Domain_Solver.md).
You can also find the example as a python script [here](https://github.com/stevengj/meep/blob/master/python/examples/solve-cw.py).

**Comment by ChristopherHogan** [comment] 2018-05-07 20:39
Your error report still contains this line:
```python
dfts = sim.add_dft_fields([mp.Ez], mp.Volume(center=mp.Vector3(), size=mp.Vector3(sxy-2dpml,sxy-2dpml)), fcen, fcen, 1)
```
As my links above show, it should be:
```python
where = mp.Volume(center=mp.Vector3(), size=mp.Vector3(sxy-2*dpml,sxy-2*dpml))
dfts = sim.add_dft_fields([mp.Ez], fcen, fcen, 1, where=where)
```

**Comment by amrit-poudel** [comment] 2018-05-07 20:42
Thanks. It worked now.  I could close this issue, however, there is one lingering issue about 2D_convergence test not converging during make check.

Since I am interested in python interface only, I hope this will have no impact my use case. Please let me know if it is otherwise.

**Comment by JeanRintoul** [comment] 2018-05-08 23:53
I'm having trouble running this, I'm using OSX and installed Meep via Conda install (conda create -n mp -c chogan -c defaults -c conda-forge pymeep" 

Is there any chance of getting an updated conda install that can run this example? 

I've tried compiling from source via these directions: https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05811.html but GUILE is not happy and it looks like a long slow road. Running Meep through conda is working well, except for this example.

**Comment by ChristopherHogan** [comment] 2018-05-09 12:44
@JeanRintoul, we will update the conda package as soon as we release version 1.5, which should be very soon.

**Closed** 2019-02-11 15:03 UTC
