### ISSUE TITLE
build error with python binding

### ISSUE THREAD

**Issue by topazus** [NanoComp/meep#2511] opened 2023-05-11 09:30 UTC
detailed build process:
```
ruby in 🌐 fedora in rpmbuild/SOURCES/meep-1.26.0 
❯ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features by default... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for C++ compiler vendor... gnu
checking whether C++ compiler accepts -fstrict-aliasing... yes
checking whether C++ compiler accepts -ffast-math... yes
checking for gcc architecture flag... 
checking for x86 cpuid 0 output... 16:756e6547:6c65746e:49656e69
checking for x86 cpuid 1 output... 906ea:8100800:7ffafbbf:bfebfbff
checking whether C++ compiler accepts -mtune=native... yes
checking for gcc architecture flag... -mtune=native
checking whether C++ compiler accepts -O3 -fstrict-aliasing -mtune=native... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for sin in -lm... yes
checking for fftw_plan_dft_1d in -lfftw3... yes
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... gfortran
checking whether the compiler supports GNU Fortran 77... yes
checking whether gfortran accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fPIC
checking if gfortran PIC flag -fPIC works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-redhat-linux/13 -L/usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/13/../../.. -lfftw3 -lgfortran -lm -lquadmath
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
checking if sgemm_ is being linked in already... no
checking for sgemm_ in -lopenblas... yes
checking for cheev_... yes
checking for pkg-config... /usr/bin/pkg-config
checking for harminv >= 1.1... yes
checking HARMINV_CFLAGS... 
checking HARMINV_LIBS... -lharminv
checking for mpb.h... no
checking for cos in -lm... yes
checking for cblas_dgemm in -lgslcblas... yes
checking for gsl_sf_bessel_Jn in -lgsl... yes
checking for deflate in -lz... yes
checking for H5Pcreate in -lhdf5... yes
checking for H5Pcreate... yes
checking for hdf5.h... yes
checking for H5Pset_mpi... no
checking for H5Pset_fapl_mpio... no
checking for guile-config... guile-config
checking if linking to guile works... yes
checking for libguile.h... yes
checking for guile/gh.h... no
checking for scm_make_smob_type... yes
checking for SCM_SMOB_PREDICATE... no
checking for SCM_SMOB_DATA... no
checking for SCM_NEWSMOB... no
checking how to activate readline in Guile... ice-9 readline
checking for libctl dir... /usr/share/libctl
checking for gen-ctl-io... gen-ctl-io
checking for ctl_get_vector3 in -lctl... yes
checking for ctl.h... yes
checking whether libctl version is at least 4.2.0... ok
checking for libctl_quiet feature... yes
checking for vector3_dot in -lctlgeom... yes
checking for libGDSII.h... no
checking for feenableexcept... yes
checking whether feenableexcept declaration is usable... yes
checking whether to catch and ignore SIGFPE signals... no
checking for sys/time.h... yes
checking for immintrin.h... yes
checking for BSDgettimeofday... no
checking for gettimeofday... yes
checking for cblas_ddot... yes
checking for cblas_daxpy... yes
checking for jn... yes
checking for C/C++ restrict keyword... no
checking for swig... swig
checking for python... /usr/bin/python
checking for python version... 3.11
checking for python platform... linux
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.11/site-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib64/python3.11/site-packages
checking for Python include directory... /usr/include/python3.11
checking for Python.h... yes
checking for Numpy include directory... /usr/lib64/python3.11/site-packages/numpy/core/include
checking for numpy/arrayobject.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating scheme/Makefile
config.status: creating scheme/meep.scm
config.status: creating libpympb/Makefile
config.status: creating python/Makefile
config.status: creating Makefile
config.status: creating meep-pkgconfig
config.status: creating src/Makefile
config.status: creating src/support/Makefile
config.status: creating tests/Makefile
config.status: creating src/meep/meep-config.h
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

ruby in 🌐 fedora in rpmbuild/SOURCES/meep-1.26.0 via C v13.0.1-gcc took 8s 
❯ make -j6
make  all-recursive
make[1]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0'
Making all in src
make[2]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
make  all-recursive
make[3]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
Making all in support
make[4]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src/support'
  CC       mt19937ar.lo
  CCLD     libsupport.la
make[4]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src/support'
make[4]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
  CXX      sphere-quad.o
  CXX      array_slice.lo
  CXX      anisotropic_averaging.lo
  CXX      boundaries.lo
  CXX      bicgstab.lo
  CXX      bands.lo
  CXX      casimir.lo
  CXX      dft.lo
  CXX      cw_fields.lo
  CXX      dft_ldos.lo
  CXX      energy_and_flux.lo
  CXX      fields.lo
  CXX      fields_dump.lo
  CXX      fix_boundary_sources.lo
  CXX      loop_in_chunks.lo
  CXX      h5fields.lo
  CXX      h5file.lo
  CXX      initialize.lo
  CXX      integrate.lo
  CXX      integrate2.lo
  CXX      material_data.lo
  CXX      monitor.lo
  CXX      mympi.lo
  CXX      multilevel-atom.lo
  CXX      near2far.lo
  CXX      random.lo
  CXX      output_directory.lo
  CXX      sources.lo
  CXX      step.lo
  CXX      step_db.lo
  CXX      stress.lo
  CXX      structure.lo
  CXX      structure_dump.lo
  CXX      susceptibility.lo
  CXX      time.lo
  CXX      update_eh.lo
  CXX      mpb.lo
  CXX      update_pols.lo
  CXX      vec.lo
  CXX      step_generic.lo
  CXX      meepgeom.lo
  CXX      GDSIIgeom.lo
  CXX      step_generic_stride1.lo
meepgeom.cpp: In function 'std::complex<double> meep_geom::cond_cmp(meep::component, const meep::vec&, double, geom_epsilon*)':
meepgeom.cpp:2617:1: warning: control reaches end of non-void function [-Wreturn-type]
 2617 | }
      | ^
  CXXLD    sphere_quad
  CXXLD    libmeep.la
make[4]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
make[3]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
make[2]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/src'
Making all in tests
make[2]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/tests'
Making all in scheme
make[2]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/scheme'
gen-ctl-io --cxx --header -o ctl-io.h meep.scm /usr/share/libctl
gen-ctl-io --cxx --swig -o ctl-io.i meep.scm /usr/share/libctl
cp -f /usr/share/libctl/base/main.c main.cpp
cp -f /usr/share/libctl/utils/geom.c geom.cpp
gen-ctl-io --cxx --code -o ctl-io.cpp meep.scm /usr/share/libctl
make  all-am
make[3]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/scheme'
  CXX      meep-meep.o
  CXX      meep-structure.o
  CXX      meep-meep_wrap.o
  CXX      meep-geom.o
  CXX      meep-main.o
  CXX      meep-ctl-io.o
meep_wrap.cxx:1513: warning: "SCM_VECTORP" redefined
 1513 | #  define SCM_VECTORP(o) scm_vector_p(o)
      | 
In file included from /usr/include/guile/2.0/libguile.h:126,
                 from meep_wrap.cxx:752:
/usr/include/guile/2.0/libguile/deprecated.h:475: note: this is the location of the previous definition
  475 | #define SCM_VECTORP(x)         scm_i_vectorp(x)
      | 
meep_wrap.cxx:1514: warning: "SCM_VECTOR_LENGTH" redefined
 1514 | #  define SCM_VECTOR_LENGTH(o) scm_c_vector_length(o)
      | 
/usr/include/guile/2.0/libguile/deprecated.h:476: note: this is the location of the previous definition
  476 | #define SCM_VECTOR_LENGTH(x)   scm_i_vector_length(x)
      | 
geom.cpp:22: warning: "_GNU_SOURCE" redefined
   22 | #define _GNU_SOURCE
      | 
<command-line>: note: this is the location of the previous definition
  CXXLD    meep
make[3]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/scheme'
make[2]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/scheme'
Making all in python
make[2]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/python'
make  all-am
make[3]: Entering directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/python'
  CXX      _meep_la-meep-python.lo
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_mdata_set(PyObject*, PyObject*)':
meep-python.cxx:141689:3: error: 'maxwell_data' was not declared in this scope
141689 |   maxwell_data *arg2 = (maxwell_data *) 0 ;
       |   ^~~~~~~~~~~~
meep-python.cxx:141689:17: error: 'arg2' was not declared in this scope; did you mean 'arg1'?
141689 |   maxwell_data *arg2 = (maxwell_data *) 0 ;
       |                 ^~~~
       |                 arg1
meep-python.cxx:141689:39: error: expected primary-expression before ')' token
141689 |   maxwell_data *arg2 = (maxwell_data *) 0 ;
       |                                       ^
meep-python.cxx:141707:28: error: 'maxwell_data' does not name a type
141707 |   arg2 = reinterpret_cast< maxwell_data * >(argp2);
       |                            ^~~~~~~~~~~~
meep-python.cxx:141707:41: error: expected '>' before '*' token
141707 |   arg2 = reinterpret_cast< maxwell_data * >(argp2);
       |                                         ^
meep-python.cxx:141707:41: error: expected '(' before '*' token
141707 |   arg2 = reinterpret_cast< maxwell_data * >(argp2);
       |                                         ^
       |                                         (
meep-python.cxx:141707:43: error: expected primary-expression before '>' token
141707 |   arg2 = reinterpret_cast< maxwell_data * >(argp2);
       |                                           ^
meep-python.cxx:141707:51: error: expected ')' before ';' token
141707 |   arg2 = reinterpret_cast< maxwell_data * >(argp2);
       |                                                   ^
       |                                                   )
meep-python.cxx:141708:21: error: 'struct meep::eigenmode_data' has no member named 'mdata'
141708 |   if (arg1) (arg1)->mdata = arg2;
       |                     ^~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_mdata_get(PyObject*, PyObject*)':
meep-python.cxx:141722:3: error: 'maxwell_data' was not declared in this scope
141722 |   maxwell_data *result = 0 ;
       |   ^~~~~~~~~~~~
meep-python.cxx:141722:17: error: 'result' was not declared in this scope
141722 |   maxwell_data *result = 0 ;
       |                 ^~~~~~
meep-python.cxx:141730:27: error: expected primary-expression before ')' token
141730 |   result = (maxwell_data *) ((arg1)->mdata);
       |                           ^
meep-python.cxx:141730:38: error: 'struct meep::eigenmode_data' has no member named 'mdata'
141730 |   result = (maxwell_data *) ((arg1)->mdata);
       |                                      ^~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_fft_data_H_set(PyObject*, PyObject*)':
meep-python.cxx:141741:3: error: 'scalar_complex' was not declared in this scope
141741 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |   ^~~~~~~~~~~~~~
meep-python.cxx:141741:19: error: 'arg2' was not declared in this scope; did you mean 'arg1'?
141741 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |                   ^~~~
       |                   arg1
meep-python.cxx:141741:43: error: expected primary-expression before ')' token
141741 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |                                           ^
meep-python.cxx:141759:28: error: 'scalar_complex' does not name a type
141759 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                            ^~~~~~~~~~~~~~
meep-python.cxx:141759:43: error: expected '>' before '*' token
141759 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                           ^
meep-python.cxx:141759:43: error: expected '(' before '*' token
141759 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                           ^
       |                                           (
meep-python.cxx:141759:45: error: expected primary-expression before '>' token
141759 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                             ^
meep-python.cxx:141759:53: error: expected ')' before ';' token
141759 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                                     ^
       |                                                     )
meep-python.cxx:141760:21: error: 'struct meep::eigenmode_data' has no member named 'fft_data_H'
141760 |   if (arg1) (arg1)->fft_data_H = arg2;
       |                     ^~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_fft_data_H_get(PyObject*, PyObject*)':
meep-python.cxx:141774:3: error: 'scalar_complex' was not declared in this scope
141774 |   scalar_complex *result = 0 ;
       |   ^~~~~~~~~~~~~~
meep-python.cxx:141774:19: error: 'result' was not declared in this scope
141774 |   scalar_complex *result = 0 ;
       |                   ^~~~~~
meep-python.cxx:141782:29: error: expected primary-expression before ')' token
141782 |   result = (scalar_complex *) ((arg1)->fft_data_H);
       |                             ^
meep-python.cxx:141782:40: error: 'struct meep::eigenmode_data' has no member named 'fft_data_H'
141782 |   result = (scalar_complex *) ((arg1)->fft_data_H);
       |                                        ^~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_fft_data_E_set(PyObject*, PyObject*)':
meep-python.cxx:141793:3: error: 'scalar_complex' was not declared in this scope
141793 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |   ^~~~~~~~~~~~~~
meep-python.cxx:141793:19: error: 'arg2' was not declared in this scope; did you mean 'arg1'?
141793 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |                   ^~~~
       |                   arg1
meep-python.cxx:141793:43: error: expected primary-expression before ')' token
141793 |   scalar_complex *arg2 = (scalar_complex *) 0 ;
       |                                           ^
meep-python.cxx:141811:28: error: 'scalar_complex' does not name a type
141811 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                            ^~~~~~~~~~~~~~
meep-python.cxx:141811:43: error: expected '>' before '*' token
141811 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                           ^
meep-python.cxx:141811:43: error: expected '(' before '*' token
141811 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                           ^
       |                                           (
meep-python.cxx:141811:45: error: expected primary-expression before '>' token
141811 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                             ^
meep-python.cxx:141811:53: error: expected ')' before ';' token
141811 |   arg2 = reinterpret_cast< scalar_complex * >(argp2);
       |                                                     ^
       |                                                     )
meep-python.cxx:141812:21: error: 'struct meep::eigenmode_data' has no member named 'fft_data_E'
141812 |   if (arg1) (arg1)->fft_data_E = arg2;
       |                     ^~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_fft_data_E_get(PyObject*, PyObject*)':
meep-python.cxx:141826:3: error: 'scalar_complex' was not declared in this scope
141826 |   scalar_complex *result = 0 ;
       |   ^~~~~~~~~~~~~~
meep-python.cxx:141826:19: error: 'result' was not declared in this scope
141826 |   scalar_complex *result = 0 ;
       |                   ^~~~~~
meep-python.cxx:141834:29: error: expected primary-expression before ')' token
141834 |   result = (scalar_complex *) ((arg1)->fft_data_E);
       |                             ^
meep-python.cxx:141834:40: error: 'struct meep::eigenmode_data' has no member named 'fft_data_E'
141834 |   result = (scalar_complex *) ((arg1)->fft_data_E);
       |                                        ^~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_H_set(PyObject*, PyObject*)':
meep-python.cxx:141845:3: error: 'evectmatrix' was not declared in this scope
141845 |   evectmatrix arg2 ;
       |   ^~~~~~~~~~~
meep-python.cxx:141867:21: error: 'temp' was not declared in this scope; did you mean 'tm'?
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                     ^~~~
       |                     tm
meep-python.cxx:141867:46: error: 'evectmatrix' does not name a type
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                                              ^~~~~~~~~~~
meep-python.cxx:141867:58: error: expected '>' before '*' token
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                                                          ^
meep-python.cxx:141867:58: error: expected '(' before '*' token
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                                                          ^
       |                                                          (
meep-python.cxx:141867:60: error: expected primary-expression before '>' token
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                                                            ^
meep-python.cxx:141867:68: error: expected ')' before ';' token
141867 |       evectmatrix * temp = reinterpret_cast< evectmatrix * >(argp2);
       |                                                                    ^
       |                                                                    )
meep-python.cxx:141868:7: error: 'arg2' was not declared in this scope; did you mean 'argp2'?
141868 |       arg2 = *temp;
       |       ^~~~
       |       argp2
meep-python.cxx:141869:32: error: type '<type error>' argument given to 'delete', expected pointer
141869 |       if (SWIG_IsNewObj(res2)) delete temp;
       |                                ^~~~~~~~~~~
meep-python.cxx:141872:21: error: 'struct meep::eigenmode_data' has no member named 'H'
141872 |   if (arg1) (arg1)->H = arg2;
       |                     ^
meep-python.cxx:141872:25: error: 'arg2' was not declared in this scope; did you mean 'argp2'?
141872 |   if (arg1) (arg1)->H = arg2;
       |                         ^~~~
       |                         argp2
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_H_get(PyObject*, PyObject*)':
meep-python.cxx:141886:3: error: 'evectmatrix' was not declared in this scope
141886 |   evectmatrix result;
       |   ^~~~~~~~~~~
meep-python.cxx:141894:3: error: 'result' was not declared in this scope
141894 |   result =  ((arg1)->H);
       |   ^~~~~~
meep-python.cxx:141894:22: error: 'struct meep::eigenmode_data' has no member named 'H'
141894 |   result =  ((arg1)->H);
       |                      ^
meep-python.cxx:141895:39: error: expected type-specifier before 'evectmatrix'
141895 |   resultobj = SWIG_NewPointerObj((new evectmatrix(result)), SWIGTYPE_p_evectmatrix, SWIG_POINTER_OWN |  0 );
       |                                       ^~~~~~~~~~~
meep-python.cxx:1084:89: note: in definition of macro 'SWIG_NewPointerObj'
 1084 | #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
      |                                                                                         ^~~
meep-python.cxx:141895:39: error: expected ')' before 'evectmatrix'
141895 |   resultobj = SWIG_NewPointerObj((new evectmatrix(result)), SWIGTYPE_p_evectmatrix, SWIG_POINTER_OWN |  0 );
       |                                  ~    ^~~~~~~~~~~
meep-python.cxx:1084:89: note: in definition of macro 'SWIG_NewPointerObj'
 1084 | #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
      |                                                                                         ^~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_n_set(PyObject*, PyObject*)':
meep-python.cxx:141930:51: error: 'struct meep::eigenmode_data' has no member named 'n'
141930 |       for (; ii < (size_t)3; ++ii) *(int *)&arg1->n[ii] = *((int *)arg2 + ii);
       |                                                   ^
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_n_get(PyObject*, PyObject*)':
meep-python.cxx:141956:36: error: 'struct meep::eigenmode_data' has no member named 'n'
141956 |   result = (int *)(int *) ((arg1)->n);
       |                                    ^
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_s_set(PyObject*, PyObject*)':
meep-python.cxx:141992:54: error: 'struct meep::eigenmode_data' has no member named 's'
141992 |       for (; ii < (size_t)3; ++ii) *(double *)&arg1->s[ii] = *((double *)arg2 + ii);
       |                                                      ^
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_s_get(PyObject*, PyObject*)':
meep-python.cxx:142018:42: error: 'struct meep::eigenmode_data' has no member named 's'
142018 |   result = (double *)(double *) ((arg1)->s);
       |                                          ^
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_Gk_set(PyObject*, PyObject*)':
meep-python.cxx:142054:54: error: 'struct meep::eigenmode_data' has no member named 'Gk'
142054 |       for (; ii < (size_t)3; ++ii) *(double *)&arg1->Gk[ii] = *((double *)arg2 + ii);
       |                                                      ^~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_Gk_get(PyObject*, PyObject*)':
meep-python.cxx:142080:42: error: 'struct meep::eigenmode_data' has no member named 'Gk'
142080 |   result = (double *)(double *) ((arg1)->Gk);
       |                                          ^~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_center_set(PyObject*, PyObject*)':
meep-python.cxx:142110:21: error: 'struct meep::eigenmode_data' has no member named 'center'
142110 |   if (arg1) (arg1)->center = *arg2;
       |                     ^~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_center_get(PyObject*, PyObject*)':
meep-python.cxx:142132:36: error: 'struct meep::eigenmode_data' has no member named 'center'
142132 |   result = (meep::vec *)& ((arg1)->center);
       |                                    ^~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_amp_func_set(PyObject*, PyObject*)':
meep-python.cxx:142170:21: error: 'struct meep::eigenmode_data' has no member named 'amp_func'
142170 |   if (arg1) (arg1)->amp_func = arg2;
       |                     ^~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_amp_func_get(PyObject*, PyObject*)':
meep-python.cxx:142192:22: error: 'struct meep::eigenmode_data' has no member named 'amp_func'
142192 |   result =  ((arg1)->amp_func);
       |                      ^~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_band_num_set(PyObject*, PyObject*)':
meep-python.cxx:142222:21: error: 'struct meep::eigenmode_data' has no member named 'band_num'
142222 |   if (arg1) (arg1)->band_num = arg2;
       |                     ^~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_band_num_get(PyObject*, PyObject*)':
meep-python.cxx:142244:27: error: 'struct meep::eigenmode_data' has no member named 'band_num'
142244 |   result = (int) ((arg1)->band_num);
       |                           ^~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_frequency_set(PyObject*, PyObject*)':
meep-python.cxx:142274:21: error: 'struct meep::eigenmode_data' has no member named 'frequency'
142274 |   if (arg1) (arg1)->frequency = arg2;
       |                     ^~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_frequency_get(PyObject*, PyObject*)':
meep-python.cxx:142296:30: error: 'struct meep::eigenmode_data' has no member named 'frequency'
142296 |   result = (double) ((arg1)->frequency);
       |                              ^~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_group_velocity_set(PyObject*, PyObject*)':
meep-python.cxx:142326:21: error: 'struct meep::eigenmode_data' has no member named 'group_velocity'
142326 |   if (arg1) (arg1)->group_velocity = arg2;
       |                     ^~~~~~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap_eigenmode_data_group_velocity_get(PyObject*, PyObject*)':
meep-python.cxx:142348:30: error: 'struct meep::eigenmode_data' has no member named 'group_velocity'
142348 |   result = (double) ((arg1)->group_velocity);
       |                              ^~~~~~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap__get_eigenmode(PyObject*, PyObject*)':
meep-python.cxx:142552:54: error: void value not ignored as it ought to be
142552 |       result = (meep::eigenmode_data *)_get_eigenmode(arg1,arg2,arg3,SWIG_STD_MOVE(arg4),SWIG_STD_MOVE(arg5),arg6,(meep::vec const &)*arg7,arg8,arg9,arg10,arg11,arg12);
       |                                        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
meep-python.cxx: In function 'PyObject* _wrap__get_eigenmode_Gk(PyObject*, PyObject*)':
meep-python.cxx:142581:28: error: '_get_eigenmode_Gk' was not declared in this scope; did you mean '_get_eigenmode'?
142581 |       result = (PyObject *)_get_eigenmode_Gk(arg1);
       |                            ^~~~~~~~~~~~~~~~~
       |                            _get_eigenmode
make[3]: *** [Makefile:903: _meep_la-meep-python.lo] Error 1
make[3]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/python'
make[2]: *** [Makefile:756: all] Error 2
make[2]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0/python'
make[1]: *** [Makefile:518: all-recursive] Error 1
make[1]: Leaving directory '/home/ruby/rpmbuild/SOURCES/meep-1.26.0'
make: *** [Makefile:425: all] Error 2
```

**Comment by smartalecH** [comment] 2023-05-11 14:06
Looks like you aren't building with MPB. Try building on `master`. #2486 should address this.

**Comment by stevengj** [comment] 2023-05-11 14:51
Duplicate of https://github.com/NanoComp/meep/issues/2485.

**Closed by stevengj** 2023-05-11 14:51 UTC
