### ISSUE TITLE
Bad ε-averaging from Prism

### ISSUE THREAD

**Issue by jeinarsson** [NanoComp/meep#1060] opened 2019-11-22 23:25 UTC
I'm getting strange ε output from a Prism, where the vertices are generated by vectorizing a bitmap by marching squares (see [skimage.measure.find_contours](https://scikit-image.org/docs/0.16.x/api/skimage.measure.html#find-contours)). Here's a small example:

```python
import meep as mp
import numpy as np
import matplotlib.pyplot as plt
from skimage import measure

cell = mp.Vector3(3,3,0)

# The size of the array representing the level set.
# Larger L give a higher fidelity circle with more and smaller edges.
L = 75 

xs = np.linspace(-1,1,L)
ys = np.linspace(-1,1,L)
X, Y = np.meshgrid(xs,ys)
design = X**2 + Y**2 < 1.0**2

# Extract contour and transform to design space.
contours = measure.find_contours(design, level=0.5)
contour = contours[0]  # we know there's only one contour.
contour = contour[:-1,:]  # exclude last point == first point.
contour /= L
contour -= .5
contour *= 2*R
vertices = [mp.Vector3(
    x=p[0], y=p[1], z=0.0
) for p in contour]

geometry = [mp.Prism(vertices, height=1, material=mp.Medium(epsilon=10))]
resolution = 25
sim = mp.Simulation(cell_size=cell,
                    geometry=geometry,
                    resolution=resolution)

fig, ax = plt.subplots(figsize=(10,10))
mp.quiet(True) # otherwise it outputs all prism vertices.
sim.plot2D(ax=ax, eps_parameters={'interpolation': 'none', 'cmap': 'Greys'})
mp.quiet(False)

for go in sim.geometry:
  if isinstance(go, mp.Prism):
    xs = [v.x+0.5/resolution for v in go.vertices] # the translation corrects for the fact that imshow plots pixel values half pixel
    ys = [v.y+0.5/resolution for v in go.vertices] # offset compared to skimage.measure.find_contour.
    ax.plot(xs, ys,'.-')
```
Which outputs the following figure (blue curve is vertices, raster is epsilon data):
![Output 1](https://user-images.githubusercontent.com/610827/69467070-55af3a00-0d3b-11ea-97f3-fb576f14d437.png)

Without knowing more, I suspect there is some edge case (no pun intended) issue here, because all edges that come out of marching cubes are horizontal, vertical or exactly 45 degrees.

Indeed, I can do the same experiment where I generate the vertices on a "perfect circle":
```python
# Manually make a well behaved circle polygon vertices.
cell = mp.Vector3(3,3,0)
N = 200
R = 1.0
phis = np.linspace(0,2*np.pi,N+1)
vertices = []
for phi in phis[:-1]:
  vertices.append(
      mp.Vector3(
        x=R*np.cos(phi), 
        y=R*np.sin(phi),
        z=0.0,
      ))
geometry = [mp.Prism(vertices, height=1, material=mp.Medium(epsilon=10))]
resolution = 25
sim = mp.Simulation(cell_size=cell,
                    geometry=geometry,
                    resolution=resolution)

fig, ax = plt.subplots(figsize=(10,10))
mp.quiet(True)
sim.plot2D(ax=ax, eps_parameters={'interpolation': 'none', 'cmap': 'Greys'})
mp.quiet(False)
for go in sim.geometry:
  if isinstance(go, mp.Prism):
    xs = [v.x+0.5/resolution for v in go.vertices] # the translation corrects for the fact that imshow plots pixel values half pixel
    ys = [v.y+0.5/resolution for v in go.vertices] # offset compared to skimage.measure.find_contour.
    ax.plot(xs, ys,'.-')
```
Which results in the following, seemingly correct, output:
![Output 2](https://user-images.githubusercontent.com/610827/69467234-e6861580-0d3b-11ea-837d-fb12883b07de.png)

**Comment by oskooi** [comment] 2019-11-23 04:12
Perhaps @HomerReid, who added the `Prism` object initially with NanoComp/libctl#13 and later updated its `normal_to_object` function with NanoComp/libctl#19, etc., can comment?

**Comment by smartalecH** [comment] 2019-11-25 19:08
Seems to be the same issue seen in #864 and #400.

The point-in-polygon function needs some revamping to account for some of these boundary cases. It covers simple polygons (simple meaning not a lot of vertices). However, it starts to run into trouble when the vertices are very close together and are rather dense.

The point-in-polygon problem is a classic tradeoff between computational complexity and functional rigor -- before someone dives in to revamp the routine, we should do some thorough literature searching. Perhaps even use an existing library instead? Long story short, not a trivial fix that will happen overnight.

**Comment by jeinarsson** [comment] 2019-11-25 22:04
Agree that computational geometry is very hard to get (robustly) right.

It's a big decision to link against a large external library, but we could consider CGAL, in particular see https://doc.cgal.org/latest/Polygon/index.html 

Thoughts?


In this particular case I have a feeling (untested) that the test rays intersect a whole vertical segment, ie crossing both vertices, and thereby miscounting the number of intersections.

**Comment by stevengj** [comment] 2019-11-26 02:55
Closing as a duplicate of #864

**Closed by stevengj** 2019-11-26 02:55 UTC
Labels: duplicate
