### ISSUE TITLE
Python: progress tracking error with `bend-flux.py` tutorial

### ISSUE THREAD

**Issue by ecmjohnson** [NanoComp/meep#1160] opened 2020-03-26 13:03 UTC
I'm using meep from tag 1.31.1 and I encounter an error while trying to run the unmodified `bend-flux.py` example. I was successfully able to run all the tutorial examples prior to this (which admittedly is only one or two). When I run this example, I get the following error:
```
[ecmjohnson@GenericComputerName examples]$ python bend-flux.py 
-----------
Initializing structure...
time for choose_chunkdivision = 0.002105 s
Working in 2D dimensions.
Computational cell is 16 x 32 x 0 with resolution 10
     block, center = (0,-11.5,0)
          size (1e+20,1,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 0.21156 s
-----------
field decay(t = 50.050000000000004): 4.825189380557793e-09 / 4.825189380557793e-09 = 1.0
on time step 1773 (time=88.65), 0.00225686 s/step
field decay(t = 100.05000000000001): 0.0288018098794258 / 0.0288018098794258 = 1.0
field decay(t = 150.1): 0.026893465093385728 / 0.0288018098794258 = 0.933742192104279
on time step 3587 (time=179.35), 0.00220567 s/step
field decay(t = 200.15): 2.3158397323771355e-13 / 0.0288018098794258 = 8.040604885845821e-12
Traceback (most recent call last):
  File "bend-flux.py", line 54, in <module>
    sim.run(until_after_sources=mp.stop_when_fields_decayed(50,mp.Ez,pt,1e-3))
  File "/usr/local/lib/python3.7/site-packages/meep/simulation.py", line 2232, in run
    self._run_sources_until(until_after_sources, step_funcs)
  File "/usr/local/lib/python3.7/site-packages/meep/simulation.py", line 1520, in _run_sources_until
    self._run_until(new_conds, step_funcs)
  File "/usr/local/lib/python3.7/site-packages/meep/simulation.py", line 1496, in _run_until
    self.progress.value = t0 + stop_time
UnboundLocalError: local variable 't0' referenced before assignment

Elapsed run time = 9.5707 s
```

I am able to run this example successfully (i.e. output figure is qualitatively correct) by removing the following block relating to updating the progress tracker for the one extra iteration required by `_run_until` to match scheme in `simulation.py` (judging by [this comment](https://github.com/NanoComp/meep/blob/0d4656c7778b526a535d37fc9898c83bfb3bdb74/python/simulation.py#L1488)):
```
if do_progress:
    self.progress.value = t0 + stop_time
    self.progress.description = "100% done "
```
I have not tested if this error exists with the master branch, but I did verify that the above block still exists in [master](https://github.com/NanoComp/meep/blob/0d4656c7778b526a535d37fc9898c83bfb3bdb74/python/simulation.py#L1497) as of today.

It appears somehow that `t0`, `stop_time`, and `progress` are referenced before their assignments. I tried removing just the first line of the `if` statement and this still resulted in an error (i.e. `AttributeError: 'Simulation' object has no attribute 'progress'`). I also verified that `len(cond)` is 1 at that point of execution, so the earlier `for` loop in `_run_until` should have set all these variables.

Thanks!

**Comment by ecmjohnson** [comment] 2020-03-26 13:26
The same issue occurs for the `refl-angular.py` example, so I'm assuming this issue occurs with all instances of using `until_after_sources`

**Comment by stevengj** [comment] 2020-03-31 01:19
Thanks, duplicate of #1164.

**Closed by stevengj** 2020-03-31 01:19 UTC
Labels: bug
