### ISSUE TITLE
default-material not being reset in Scheme following reset-meep

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#731] opened 2019-02-20 17:17 UTC
The parameter [`default-material`](https://meep.readthedocs.io/en/latest/Scheme_User_Interface/#input-variables) is not being reset in Scheme following `(reset-meep)` unlike the other input variables. This is demonstrated in the following example for a binary grating.

```scm
(set-param! resolution 25)  ; pixels/μm                                                                                                                         

(define-param dpml 1.0)     ; PML thickness                                                                                                                     
(define-param dsub 3.0)     ; substrate thickness                                                                                                               
(define-param dpad 3.0)     ; padding between grating and PML                                                                                                   
(define-param gp 10.0)      ; grating period                                                                                                                    
(define-param gh 0.5)       ; grating height                                                                                                                    
(define-param gdc 0.5)      ; grating duty cycle                                                                                                                

(define sx (+ dpml dsub gh dpad dpml))
(define sy gp)

(define cell (make lattice (size sx sy 0)))
(set! geometry-lattice cell)

(define boundary-layers (list (make pml (thickness dpml) (direction X))))
(set! pml-layers boundary-layers)

(define-param wvl-min 0.4)          ; min wavelength                                                                                                            
(define-param wvl-max 0.6)          ; max wavelength                                                                                                            
(define fmin (/ wvl-max))           ; min frequency                                                                                                             
(define fmax (/ wvl-min))           ; max frequency                                                                                                             
(define fcen (* 0.5 (+ fmin fmax))) ; pulse frequency center                                                                                                    
(define df (- fmax fmin))           ; pulse frequency width                                                                                                     

(define pulse-src (list (make source
                          (src (make gaussian-src (frequency fcen) (fwidth df)))
                          (component Ez)
                          (center (+ (* -0.5 sx) dpml (* 0.5 dsub)) 0 0)
                          (size 0 sy 0))))

(set! sources pulse-src)

(set! k-point (vector3 0 0 0))

(define glass (make medium (index 1.5)))
(set! default-material glass)

(define symm (list (make mirror-sym (direction Y))))
(set! symmetries symm)

(init-fields)
(reset-meep)

(set! geometry-lattice cell)

(set! pml-layers boundary-layers)

(set! sources pulse-src)

(set! k-point (vector3 0 0 0))

(set! default-material air)

(set! geometry (list (make block
                       (material glass)
                       (size (+ dpml dsub) infinity infinity)
                       (center (+ (* -0.5 sx) (* 0.5 (+ dpml dsub))) 0 0))
                     (make block
                       (material glass)
                       (size gh (* gdc gp) infinity)
                       (center (+ (* -0.5 sx) dpml dsub (* 0.5 gh)) 0 0))))

(set! symmetries symm)

(run-until 0 (at-beginning output-epsilon))
```

The simulation consists of two runs involving an empty cell followed by the binary grating. `(set! default-material glass)` is used in the first run but must be followed by `(set! default-material air)` in the second run.  There is no change in `default-material` following `reset-meep`. This is a bug: the line `(set! default-material air)` in the second run should be unnecessary since `default-material` should revert to `air` (the default).

**Comment by ChristopherHogan** [comment] 2019-02-20 17:30
@oskooi, do you remember `(reset-meep)` working correctly in the past (before libmeepgeom was merged into libmeep), or is this the first time you've tried it?

**Comment by oskooi** [comment] 2019-02-20 17:40
`(reset-meep)` has never been properly tested mainly because the Scheme convention for flux, etc calculations has involved calling the same script twice in *separate* runs to compute the normalization and scattering results. In the [mode decomposition tutorial example](https://meep.readthedocs.io/en/latest/Scheme_Tutorials/Mode_Decomposition/) (#715) which was merged last week, I combined these two runs in a *single* file [mode-decomposition.ctl](https://github.com/NanoComp/meep/blob/master/scheme/examples/mode-decomposition.ctl) using `(reset-meep)` but that example did not involve `default-material`.

**Comment by ChristopherHogan** [comment] 2019-02-20 17:41
I see. Thanks.

**Comment by stevengj** [comment] 2019-02-27 15:54
`(reset-meep)` does not reset any input variables (`geometry`, `geometry-lattice`, `resolution`, etcetera), so it shouldn't reset `default-material` either.

The only job of `reset-meep` is to undo the field/structure allocation caused by invoking `run` or similar.

**Closed by stevengj** 2019-02-27 15:54 UTC
Labels: bug
