### ISSUE TITLE
bad_alloc error for specific cell sizes

### ISSUE THREAD

**Issue by ThomasAuzinger** [NanoComp/meep#802] opened 2019-04-05 13:03 UTC
I encountered an error with the latest PyMeep version
```
pymeep   1.8.0   nompi_py36_nomklh8bc8a54_103  [nomkl]  chogan
```
from conda.

The output of the following script
```python
import meep as mp

resolution = 36.
working_cell_sizes = [mp.Vector3(10., 3. / resolution,  9.),
                      mp.Vector3(10., 5. / resolution,  9.),
                      mp.Vector3(10., 4. / resolution,  8.),
                      mp.Vector3(10., 4. / resolution, 10.)]
faulty_cell_size = mp.Vector3(10., 4. / resolution, 9.)

for cell_size in working_cell_sizes:
    sim = mp.Simulation(cell_size=mp.Vector3(10., 3. / resolution, 9.),
                        resolution=resolution)
    sim.run(until=1.)

sim = mp.Simulation(cell_size=faulty_cell_size,
                    resolution=resolution)
sim.run(until=1.)
```
is
```
-----------
Initializing structure...
Working in 3D dimensions.
Computational cell is 10 x 0.0833333 x 9 with resolution 36
time for set_epsilon = 0.764125 s
-----------
run 0 finished at t = 1.0 (72 timesteps)

-----------
Initializing structure...
Working in 3D dimensions.
Computational cell is 10 x 0.0833333 x 9 with resolution 36
time for set_epsilon = 0.785701 s
-----------
run 0 finished at t = 1.0 (72 timesteps)

-----------
Initializing structure...
Working in 3D dimensions.
Computational cell is 10 x 0.0833333 x 9 with resolution 36
time for set_epsilon = 0.785817 s
-----------
run 0 finished at t = 1.0 (72 timesteps)

-----------
Initializing structure...
Working in 3D dimensions.
Computational cell is 10 x 0.0833333 x 9 with resolution 36
time for set_epsilon = 0.769153 s
-----------
run 0 finished at t = 1.0 (72 timesteps)

-----------
Initializing structure...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

```
During the call with `cell_size=mp.Vector3(10., 4. / resolution, 9.)` the python script consumes all system memory (i.e. around 32GB) before failing.

**Comment by ChristopherHogan** [comment] 2019-04-08 18:59
I can't reproduce this on the `master` branch. It was likely fixed by #748.

**Closed** 2019-04-08 19:01 UTC
