### ISSUE TITLE
discretization artifacts in dft_flux object

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1043] opened 2019-10-26 23:00 UTC
The following script launches a E<sub>z</sub>-polarized planewave propagating in the *x* direction in an empty 3d cell and computes the Poynting flux along each of 6 sides of a closed box. At certain `resolution` values, the flux becomes unusually large.

```py
import meep as mp

resolution = 10  ## strange output for 20, 30                                                                                                                                      

wvl = 1.0
fcen = 1/wvl

dpml = 1.0
dair = 2.0

r = 0.5

pml_layers = [mp.PML(thickness=dpml,direction=mp.X)]

symmetries = [mp.Mirror(mp.Y),
              mp.Mirror(mp.Z,phase=-1)]

sx = 2*(dpml+dair+r)
syz = 2*(dair+r)
cell_size = mp.Vector3(sx,syz,syz)

sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.2*fcen),
                     center=mp.Vector3(-0.5*sx+dpml),
                     size=mp.Vector3(0,syz,syz),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=resolution,
                    eps_averaging=False,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries)

box_xp = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r)))
box_xm = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r)))
box_yp = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r)))
box_ym = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r)))
box_zp = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0)))
box_zm = sim.add_flux(fcen, 0, 1, mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0)))

sim.run(until_after_sources=20)

print("flux:, {:.6f}, {:.6f}, {:.6f}, {:.6f}, {:.6f}, {:.6f}".format(mp.get_fluxes(box_xp)[0],
                                                                     mp.get_fluxes(box_xm)[0],
                                                                     mp.get_fluxes(box_yp)[0],
                                                                     mp.get_fluxes(box_ym)[0],
                                                                     mp.get_fluxes(box_zp)[0],
                                                                     mp.get_fluxes(box_zm)[0]))
```

**resolution=10**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000311504 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 10
time for set_epsilon = 0.0140341 s
-----------
run 0 finished at t = 70.0 (1400 timesteps)
flux:, 1.631588, 1.631588, -0.000005, 0.000005, 0.000009, -0.000009
```

**resolution=15**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Padding y to even number of grid points.
Padding z to even number of grid points.
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000395564 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 15
time for set_epsilon = 0.0436422 s
-----------
Meep progress: 62.8/70.0 = 89.7% done in 4.0s, 0.5s to go
on time step 1884 (time=62.8), 0.00212378 s/step
run 0 finished at t = 70.0 (2100 timesteps)
flux:, 1.522463, 1.522463, -0.000000, 0.000000, -0.000000, 0.000000
```

**resolution=20** (large values)
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000515274 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.0907429 s
-----------
Meep progress: 17.95/70.0 = 25.6% done in 4.0s, 11.6s to go
on time step 718 (time=17.95), 0.00557331 s/step
Meep progress: 38.15/70.0 = 54.5% done in 8.0s, 6.7s to go
on time step 1526 (time=38.15), 0.00495095 s/step
Meep progress: 58.275000000000006/70.0 = 83.2% done in 12.0s, 2.4s to go
on time step 2331 (time=58.275), 0.00496914 s/step
run 0 finished at t = 70.0 (2800 timesteps)
flux:, 1820348954164070400.000000, 1081458856371996928.000000, -82773801567460112.000000, 82773801567460112.000000, 8971776376992865280.000000, -8971776376992865280.000000
```

**resolution=25**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Padding y to even number of grid points.
Padding z to even number of grid points.
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000675202 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 25
time for set_epsilon = 0.15544 s
-----------
Meep progress: 6.82/70.0 = 9.7% done in 4.0s, 37.1s to go
on time step 341 (time=6.82), 0.011742 s/step
Meep progress: 15.08/70.0 = 21.5% done in 8.0s, 29.2s to go
on time step 754 (time=15.08), 0.00970623 s/step
Meep progress: 23.34/70.0 = 33.3% done in 12.0s, 24.0s to go
on time step 1167 (time=23.34), 0.00970159 s/step
Meep progress: 31.6/70.0 = 45.1% done in 16.0s, 19.5s to go
on time step 1580 (time=31.6), 0.00970215 s/step
Meep progress: 39.86/70.0 = 56.9% done in 20.0s, 15.1s to go
on time step 1993 (time=39.86), 0.00969852 s/step
Meep progress: 48.06/70.0 = 68.7% done in 24.0s, 11.0s to go
on time step 2403 (time=48.06), 0.00977932 s/step
Meep progress: 56.24/70.0 = 80.3% done in 28.0s, 6.9s to go
on time step 2812 (time=56.24), 0.00979342 s/step
Meep progress: 64.48/70.0 = 92.1% done in 32.1s, 2.7s to go
on time step 3224 (time=64.48), 0.00972967 s/step
run 0 finished at t = 70.0 (3500 timesteps)
flux:, 1.548095, 1.548095, -0.000000, 0.000000, 0.000000, -0.000000
```

**resolution=30** (large values)
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.00104361 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 30
time for set_epsilon = 0.19811 s
-----------
Meep progress: 3.1333333333333333/70.0 = 4.5% done in 4.0s, 85.5s to go
on time step 188 (time=3.13333), 0.0213117 s/step
Meep progress: 7.216666666666667/70.0 = 10.3% done in 8.0s, 69.7s to go
on time step 433 (time=7.21667), 0.0163388 s/step
Meep progress: 11.3/70.0 = 16.1% done in 12.0s, 62.4s to go
on time step 678 (time=11.3), 0.0163496 s/step
Meep progress: 15.383333333333333/70.0 = 22.0% done in 16.0s, 56.9s to go
on time step 923 (time=15.3833), 0.0163438 s/step
Meep progress: 19.466666666666665/70.0 = 27.8% done in 20.0s, 52.0s to go
on time step 1168 (time=19.4667), 0.0163416 s/step
Meep progress: 23.55/70.0 = 33.6% done in 24.0s, 47.4s to go
on time step 1413 (time=23.55), 0.0163468 s/step
Meep progress: 27.633333333333333/70.0 = 39.5% done in 28.0s, 43.0s to go
on time step 1658 (time=27.6333), 0.0163562 s/step
Meep progress: 31.716666666666665/70.0 = 45.3% done in 32.0s, 38.7s to go
on time step 1903 (time=31.7167), 0.0163539 s/step
Meep progress: 35.8/70.0 = 51.1% done in 36.0s, 34.4s to go
on time step 2148 (time=35.8), 0.0163466 s/step
Meep progress: 39.88333333333333/70.0 = 57.0% done in 40.1s, 30.2s to go
on time step 2393 (time=39.8833), 0.0163454 s/step
Meep progress: 43.96666666666667/70.0 = 62.8% done in 44.1s, 26.1s to go
on time step 2638 (time=43.9667), 0.0163522 s/step
Meep progress: 48.05/70.0 = 68.6% done in 48.1s, 22.0s to go
on time step 2883 (time=48.05), 0.0163488 s/step
Meep progress: 52.13333333333333/70.0 = 74.5% done in 52.1s, 17.8s to go
on time step 3128 (time=52.1333), 0.0163535 s/step
Meep progress: 56.21666666666667/70.0 = 80.3% done in 56.1s, 13.7s to go
on time step 3373 (time=56.2167), 0.0163466 s/step
Meep progress: 60.3/70.0 = 86.1% done in 60.1s, 9.7s to go
on time step 3618 (time=60.3), 0.0163422 s/step
Meep progress: 64.35/70.0 = 91.9% done in 64.1s, 5.6s to go
on time step 3861 (time=64.35), 0.0164788 s/step
Meep progress: 68.43333333333334/70.0 = 97.8% done in 68.1s, 1.6s to go
on time step 4106 (time=68.4333), 0.016347 s/step
run 0 finished at t = 70.0 (4200 timesteps)
flux:, 1459390448574672659383315722416858030678581706752.000000, 88649338771690060606454862583248934889125314560.000000, 174732717817583568259904759287750632314966638592.000000, -174732717817583568259904759287750632314966638592.000000, 1524448985721283365421259838898912231715185360896.000000, -1524448985721283365421259838898912231715185360896.000000
```

**Comment by khashabri** [comment] 2019-10-28 11:09
A 2D plot of the structure at the zero position illustrates a divergent behavior of the field at interfaces between the source and the PML.
![Figure_1](https://user-images.githubusercontent.com/50481847/67671578-7f608580-f976-11e9-981c-e9b72e73eb8a.png)

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.164172 s
-----------
on time step 346 (time=8.65), 0.0115772 s/step
field decay(t = 10.025): 1.2561657469931086e-06 / 1.2561657469931086e-06 = 1.0
on time step 766 (time=19.15), 0.00953054 s/step
field decay(t = 20.05): 0.026832165502590027 / 0.026832165502590027 = 1.0
on time step 1194 (time=29.85), 0.00935908 s/step
field decay(t = 30.075000000000003): 0.25558207075666484 / 0.25558207075666484 = 1.0
on time step 1579 (time=39.475), 0.0104086 s/step
field decay(t = 40.1): 0.17857933673739687 / 0.25558207075666484 = 0.698716213577513
on time step 2000 (time=50), 0.00957593 s/step
field decay(t = 50.125): 44.59998147718695 / 44.59998147718695 = 1.0
field decay(t = 60.150000000000006): 493440246987.0412 / 493440246987.0412 = 1.0
on time step 2437 (time=60.925), 0.00916058 s/step
field decay(t = 70.175): 4.5655662395321703e+21 / 4.5655662395321703e+21 = 1.0
on time step 2857 (time=71.425), 0.00952584 s/step
field decay(t = 80.2): 5.050847031644133e+31 / 5.050847031644133e+31 = 1.0
on time step 3280 (time=82), 0.00964002 s/step
field decay(t = 90.22500000000001): 5.587708065896176e+41 / 5.587708065896176e+41 = 1.0
on time step 3720 (time=93), 0.00932618 s/step
field decay(t = 100.25): 5.163742756691271e+51 / 5.163742756691271e+51 = 1.0
on time step 4153 (time=103.825), 0.00925157 s/step
field decay(t = 110.275): 5.712479800330623e+61 / 5.712479800330623e+61 = 1.0
on time step 4560 (time=114), 0.00989643 s/step
```
The longer the simulation runs, the larger are the values. If you consider omitting `k_point=mp.Vector3()` from your simulation there is no divergent behavior anymore. 
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.164263 s
-----------
Meep progress: 9.725000000000001/70.0 = 13.9% done in 4.0s, 24.8s to go
on time step 389 (time=9.725), 0.0102984 s/step
Meep progress: 21.0/70.0 = 30.0% done in 8.1s, 19.0s to go
on time step 840 (time=21), 0.00912701 s/step
Meep progress: 32.15/70.0 = 45.9% done in 12.1s, 14.3s to go
on time step 1286 (time=32.15), 0.0089743 s/step
Meep progress: 43.45/70.0 = 62.1% done in 16.1s, 9.9s to go
on time step 1738 (time=43.45), 0.00885742 s/step
Meep progress: 54.675000000000004/70.0 = 78.1% done in 20.1s, 5.6s to go
on time step 2187 (time=54.675), 0.00892001 s/step
Meep progress: 65.65/70.0 = 93.8% done in 24.1s, 1.6s to go
on time step 2626 (time=65.65), 0.00912389 s/step
Normalizing field data...
run 0 finished at t = 70.0 (2800 timesteps)
flux:, 1.719438, 1.098674, -0.308826, 0.308826, 0.001583, -0.001583

Elapsed run time = 41.4192 s

Field time usage:
        connecting chunks: 0.400374 s
            time stepping: 14.4072 s
            communicating: 2.45451 s
        outputting fields: 0.114295 s
     Fourier transforming: 0.457792 s
          everything else: 7.81802 s


Process finished with exit code 0
```

Also using a PML on all sides (either with or without a `k_point`) would solve the divergence issue. However, please note that (for whatever reason) using PML on all sides causes a none-perfect homogeneous plane wave.
![Figure_3](https://user-images.githubusercontent.com/50481847/67673271-fb100180-f979-11e9-96d6-4a65af201fa2.png)

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.165924 s
-----------
Meep progress: 6.125/70.0 = 8.8% done in 4.0s, 41.8s to go
on time step 245 (time=6.125), 0.016348 s/step
Meep progress: 14.125/70.0 = 20.2% done in 8.0s, 31.7s to go
on time step 565 (time=14.125), 0.0125097 s/step
Meep progress: 22.125/70.0 = 31.6% done in 12.0s, 26.0s to go
on time step 885 (time=22.125), 0.0125027 s/step
Meep progress: 30.0/70.0 = 42.9% done in 24.7s, 33.0s to go
on time step 1200 (time=30), 0.0404175 s/step
Meep progress: 38.1/70.0 = 54.4% done in 28.7s, 24.1s to go
on time step 1524 (time=38.1), 0.0123677 s/step
Meep progress: 46.075/70.0 = 65.8% done in 32.8s, 17.0s to go
on time step 1843 (time=46.075), 0.0125483 s/step
Meep progress: 54.1/70.0 = 77.3% done in 36.8s, 10.8s to go
on time step 2164 (time=54.1), 0.0124693 s/step
Meep progress: 62.1/70.0 = 88.7% done in 40.8s, 5.2s to go
on time step 2484 (time=62.1), 0.0125143 s/step
Normalizing field data...
run 0 finished at t = 70.0 (2800 timesteps)
flux:, 2.682665, 3.409712, 0.187937, -0.187937, 0.171267, -0.171267

Elapsed run time = 60.7009 s

Field time usage:
        connecting chunks: 0.704119 s
            time stepping: 20.3426 s
            communicating: 6.13241 s
        outputting fields: 0.117403 s
     Fourier transforming: 0.444723 s
          everything else: 16.8733 s


Process finished with exit code 0`
```

**Comment by erikshipton** [comment] 2019-10-28 15:15
@Khashayar  Remember that you're in the nearfield of the source that is
finite size.  It will be the same exact thing as diffraction from a single
slit of the same dimensions.  Once you get far enough away
https://en.wikipedia.org/wiki/Near_and_far_field you'll see those becoming
nice plane waves.  Not sure why your first picture isn't great.  If you set
Kpoint right you'll get a perfect planewave even in the near region of the
source.  This is because the sources is now infinite extent (well looks
like it).

**Comment by m9631m** [comment] 2019-10-28 16:05
@khashabri If you just want a unidirectional source you can use a combination of magnetic and electric current sources.  This avoids putting the source exactly on top of a PML (Fig. 1). 

Sorry, I just use Scheme.

```scheme
(set! sources (list
        (make source
        (src (make continuous-src
            (wavelength source-wavelength)
            (width source_rise_time))) 
        (component Ex)
        (center 0 0 source-z)
        (amplitude 1)
        (size sx_grid sy_grid 0))

    (make source
        (src (make continuous-src
            (wavelength source-wavelength)
            (width 1))) 
        (component Hy)
        (center 0 0 source-z)
        (amplitude (* 1 (/ 1 (sqrt substrate-epsilon))))
        (size sx_grid sy_grid 0))

                ))
```
  
It might also be helpful if you add some distance between the PML and the source in fig.1.

> A 2D plot of the structure at zero position illustrates a divergent behavior of the field at interfaces between the source and the boundary.
> ![Figure_1](https://user-images.githubusercontent.com/50481847/67671578-7f608580-f976-11e9-981c-e9b72e73eb8a.png)
> 
> ```
> Using MPI version 3.1, 1 processes
> -----------
> Initializing structure...
> Halving computational cell along direction y
> Halving computational cell along direction z
> Working in 3D dimensions.
> Computational cell is 7 x 5 x 5 with resolution 20
> time for set_epsilon = 0.164172 s
> -----------
> on time step 346 (time=8.65), 0.0115772 s/step
> field decay(t = 10.025): 1.2561657469931086e-06 / 1.2561657469931086e-06 = 1.0
> on time step 766 (time=19.15), 0.00953054 s/step
> field decay(t = 20.05): 0.026832165502590027 / 0.026832165502590027 = 1.0
> on time step 1194 (time=29.85), 0.00935908 s/step
> field decay(t = 30.075000000000003): 0.25558207075666484 / 0.25558207075666484 = 1.0
> on time step 1579 (time=39.475), 0.0104086 s/step
> field decay(t = 40.1): 0.17857933673739687 / 0.25558207075666484 = 0.698716213577513
> on time step 2000 (time=50), 0.00957593 s/step
> field decay(t = 50.125): 44.59998147718695 / 44.59998147718695 = 1.0
> field decay(t = 60.150000000000006): 493440246987.0412 / 493440246987.0412 = 1.0
> on time step 2437 (time=60.925), 0.00916058 s/step
> field decay(t = 70.175): 4.5655662395321703e+21 / 4.5655662395321703e+21 = 1.0
> on time step 2857 (time=71.425), 0.00952584 s/step
> field decay(t = 80.2): 5.050847031644133e+31 / 5.050847031644133e+31 = 1.0
> on time step 3280 (time=82), 0.00964002 s/step
> field decay(t = 90.22500000000001): 5.587708065896176e+41 / 5.587708065896176e+41 = 1.0
> on time step 3720 (time=93), 0.00932618 s/step
> field decay(t = 100.25): 5.163742756691271e+51 / 5.163742756691271e+51 = 1.0
> on time step 4153 (time=103.825), 0.00925157 s/step
> field decay(t = 110.275): 5.712479800330623e+61 / 5.712479800330623e+61 = 1.0
> on time step 4560 (time=114), 0.00989643 s/step
> ```
> 
> The longer the simulation runs, the larger are the values. If you consider omitting `k_point=mp.Vector3()` from your simulation there is no divergent behavior anymore.
> 
> ```
> Using MPI version 3.1, 1 processes
> -----------
> Initializing structure...
> Halving computational cell along direction y
> Halving computational cell along direction z
> Working in 3D dimensions.
> Computational cell is 7 x 5 x 5 with resolution 20
> time for set_epsilon = 0.164263 s
> -----------
> Meep progress: 9.725000000000001/70.0 = 13.9% done in 4.0s, 24.8s to go
> on time step 389 (time=9.725), 0.0102984 s/step
> Meep progress: 21.0/70.0 = 30.0% done in 8.1s, 19.0s to go
> on time step 840 (time=21), 0.00912701 s/step
> Meep progress: 32.15/70.0 = 45.9% done in 12.1s, 14.3s to go
> on time step 1286 (time=32.15), 0.0089743 s/step
> Meep progress: 43.45/70.0 = 62.1% done in 16.1s, 9.9s to go
> on time step 1738 (time=43.45), 0.00885742 s/step
> Meep progress: 54.675000000000004/70.0 = 78.1% done in 20.1s, 5.6s to go
> on time step 2187 (time=54.675), 0.00892001 s/step
> Meep progress: 65.65/70.0 = 93.8% done in 24.1s, 1.6s to go
> on time step 2626 (time=65.65), 0.00912389 s/step
> Normalizing field data...
> run 0 finished at t = 70.0 (2800 timesteps)
> flux:, 1.719438, 1.098674, -0.308826, 0.308826, 0.001583, -0.001583
> 
> Elapsed run time = 41.4192 s
> 
> Field time usage:
>         connecting chunks: 0.400374 s
>             time stepping: 14.4072 s
>             communicating: 2.45451 s
>         outputting fields: 0.114295 s
>      Fourier transforming: 0.457792 s
>           everything else: 7.81802 s
> 
> 
> Process finished with exit code 0
> ```
> 
> Also using a PML on all sides (either with or without a `k_point`) would solve the divergence issue. However, please note that (for whatever reason) using PML on all sides causes a none-perfect homogeneous plane wave.
> ![Figure_3](https://user-images.githubusercontent.com/50481847/67673271-fb100180-f979-11e9-96d6-4a65af201fa2.png)
> 
> ```
> Using MPI version 3.1, 1 processes
> -----------
> Initializing structure...
> Halving computational cell along direction y
> Halving computational cell along direction z
> Working in 3D dimensions.
> Computational cell is 7 x 5 x 5 with resolution 20
> time for set_epsilon = 0.165924 s
> -----------
> Meep progress: 6.125/70.0 = 8.8% done in 4.0s, 41.8s to go
> on time step 245 (time=6.125), 0.016348 s/step
> Meep progress: 14.125/70.0 = 20.2% done in 8.0s, 31.7s to go
> on time step 565 (time=14.125), 0.0125097 s/step
> Meep progress: 22.125/70.0 = 31.6% done in 12.0s, 26.0s to go
> on time step 885 (time=22.125), 0.0125027 s/step
> Meep progress: 30.0/70.0 = 42.9% done in 24.7s, 33.0s to go
> on time step 1200 (time=30), 0.0404175 s/step
> Meep progress: 38.1/70.0 = 54.4% done in 28.7s, 24.1s to go
> on time step 1524 (time=38.1), 0.0123677 s/step
> Meep progress: 46.075/70.0 = 65.8% done in 32.8s, 17.0s to go
> on time step 1843 (time=46.075), 0.0125483 s/step
> Meep progress: 54.1/70.0 = 77.3% done in 36.8s, 10.8s to go
> on time step 2164 (time=54.1), 0.0124693 s/step
> Meep progress: 62.1/70.0 = 88.7% done in 40.8s, 5.2s to go
> on time step 2484 (time=62.1), 0.0125143 s/step
> Normalizing field data...
> run 0 finished at t = 70.0 (2800 timesteps)
> flux:, 2.682665, 3.409712, 0.187937, -0.187937, 0.171267, -0.171267
> 
> Elapsed run time = 60.7009 s
> 
> Field time usage:
>         connecting chunks: 0.704119 s
>             time stepping: 20.3426 s
>             communicating: 6.13241 s
>         outputting fields: 0.117403 s
>      Fourier transforming: 0.444723 s
>           everything else: 16.8733 s
> 
> 
> Process finished with exit code 0`
> ```

**Comment by stevengj** [comment] 2019-10-30 02:02
Two things to try:

1. Does it blow up with only a single mirror plane?  I feel like we've had problems for a while in 3d with 2 or more mirror planes.

2. At the problematic resolutions, can you try slightly changing the cell size so that it doesn't need to pad to an even number of pixels?  (Try both increasing *and* decreasing the cell size.)

**Comment by oskooi** [comment] 2019-11-04 21:37
Additional notes:

- both mirror-symmetry planes must be present; if just one or none, fields do not blow up
- padding the cell to an even number of pixels does *not* cause the fields to blow up (e.g. see results from above)
- `k_point=mp.Vector3()` must be present; if `False`, fields do not blow up

**Comment by stevengj** [comment] 2019-11-09 15:29
This sounds like a duplicate of #132.

**Closed by stevengj** 2019-11-09 15:29 UTC
Labels: bug

**Comment by oskooi** [comment] 2019-11-13 02:36
@stevengj's patch in #132:[comment](https://github.com/NanoComp/meep/issues/132#issuecomment-553208897) does prevent the fields from blowing up (for those resolutions in which they were blowing up) but the results seem to be no longer correct:

**resolution = 20**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000545125 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.117265 s
-----------
Meep progress: 21.55/70.0 = 30.8% done in 4.0s, 9.0s to go
on time step 862 (time=21.55), 0.00464176 s/step
Meep progress: 45.275000000000006/70.0 = 64.7% done in 8.0s, 4.4s to go
on time step 1811 (time=45.275), 0.00421906 s/step
Meep progress: 68.175/70.0 = 97.4% done in 12.0s, 0.3s to go
on time step 2727 (time=68.175), 0.00436974 s/step
run 0 finished at t = 70.0 (2800 timesteps)
flux:, 1.722099, 1.102222, -0.306813, 0.306813, 0.000000, -0.000000
```

**resolution = 30**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Halving computational cell along direction y
Halving computational cell along direction z
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.00137348 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 30
time for set_epsilon = 0.189843 s
-----------
Meep progress: 3.466666666666667/70.0 = 5.0% done in 4.0s, 76.9s to go
on time step 208 (time=3.46667), 0.019262 s/step
Meep progress: 8.05/70.0 = 11.5% done in 8.0s, 61.7s to go
on time step 483 (time=8.05), 0.014591 s/step
Meep progress: 12.566666666666666/70.0 = 18.0% done in 12.0s, 54.9s to go
on time step 754 (time=12.5667), 0.0147675 s/step
Meep progress: 17.166666666666668/70.0 = 24.5% done in 16.0s, 49.3s to go
on time step 1030 (time=17.1667), 0.0145102 s/step
Meep progress: 21.75/70.0 = 31.1% done in 20.0s, 44.4s to go
on time step 1305 (time=21.75), 0.0145727 s/step
Meep progress: 26.333333333333332/70.0 = 37.6% done in 24.0s, 39.9s to go
on time step 1580 (time=26.3333), 0.0145907 s/step
Meep progress: 30.916666666666668/70.0 = 44.2% done in 28.1s, 35.5s to go
on time step 1855 (time=30.9167), 0.0145681 s/step
Meep progress: 35.483333333333334/70.0 = 50.7% done in 32.1s, 31.2s to go
on time step 2129 (time=35.4833), 0.0146183 s/step
Meep progress: 40.05/70.0 = 57.2% done in 36.1s, 27.0s to go
on time step 2403 (time=40.05), 0.0146394 s/step
Meep progress: 44.65/70.0 = 63.8% done in 40.1s, 22.8s to go
on time step 2679 (time=44.65), 0.0145433 s/step
Meep progress: 49.18333333333333/70.0 = 70.3% done in 44.1s, 18.7s to go
on time step 2951 (time=49.1833), 0.014741 s/step
Meep progress: 53.733333333333334/70.0 = 76.8% done in 48.1s, 14.6s to go
on time step 3224 (time=53.7333), 0.0147039 s/step
Meep progress: 58.31666666666666/70.0 = 83.3% done in 52.1s, 10.4s to go
on time step 3499 (time=58.3167), 0.0145976 s/step
Meep progress: 62.833333333333336/70.0 = 89.8% done in 56.1s, 6.4s to go
on time step 3770 (time=62.8333), 0.0147624 s/step
Meep progress: 67.41666666666667/70.0 = 96.3% done in 60.1s, 2.3s to go
on time step 4045 (time=67.4167), 0.0145634 s/step
run 0 finished at t = 70.0 (4200 timesteps)
flux:, 1.720388, 1.092416, -0.312579, 0.312579, 0.000000, -0.000000
```

Notice the difference in the `flux` output values at the end when compared with those from [above](https://github.com/NanoComp/meep/issues/1043#issue-512895832).

**Comment by oskooi** [comment] 2019-11-13 02:40
As a sanity check, the results *without* symmetry for the case in which the fields were blowing up (i.e. `resolution = 20`) are closer to what is expected but different than the results with symmetry and the patch referenced above:

**resolution = 20**
```
Using MPI version 3.1, 3 processes
-----------
Initializing structure...
Splitting into 3 chunks evenly
time for choose_chunkdivision = 0.000580241 s
Working in 3D dimensions.
Computational cell is 7 x 5 x 5 with resolution 20
time for set_epsilon = 0.231503 s
-----------
Meep progress: 4.55/70.0 = 6.5% done in 4.0s, 57.7s to go
on time step 182 (time=4.55), 0.0220522 s/step
Meep progress: 10.025/70.0 = 14.3% done in 8.0s, 48.0s to go
on time step 401 (time=10.025), 0.0183317 s/step
Meep progress: 15.475000000000001/70.0 = 22.1% done in 12.0s, 42.4s to go
on time step 619 (time=15.475), 0.0183964 s/step
Meep progress: 20.925/70.0 = 29.9% done in 16.1s, 37.7s to go
on time step 837 (time=20.925), 0.018418 s/step
Meep progress: 26.400000000000002/70.0 = 37.7% done in 20.1s, 33.1s to go
on time step 1056 (time=26.4), 0.0183278 s/step
Meep progress: 31.85/70.0 = 45.5% done in 24.1s, 28.8s to go
on time step 1274 (time=31.85), 0.0184101 s/step
Meep progress: 37.300000000000004/70.0 = 53.3% done in 28.1s, 24.6s to go
on time step 1492 (time=37.3), 0.0183776 s/step
Meep progress: 42.775000000000006/70.0 = 61.1% done in 32.1s, 20.4s to go
on time step 1711 (time=42.775), 0.0183354 s/step
Meep progress: 48.25/70.0 = 68.9% done in 36.1s, 16.3s to go
on time step 1930 (time=48.25), 0.0183305 s/step
Meep progress: 53.725/70.0 = 76.8% done in 40.1s, 12.2s to go
on time step 2149 (time=53.725), 0.0183264 s/step
Meep progress: 59.175000000000004/70.0 = 84.5% done in 44.1s, 8.1s to go
on time step 2367 (time=59.175), 0.0183963 s/step
Meep progress: 64.375/70.0 = 92.0% done in 48.1s, 4.2s to go
on time step 2575 (time=64.375), 0.0192491 s/step
Meep progress: 69.8/70.0 = 99.7% done in 52.2s, 0.1s to go
on time step 2792 (time=69.8), 0.0185085 s/step
run 0 finished at t = 70.0 (2800 timesteps)
flux:, 1.578848, 1.578848, -0.000000, -0.000000, -0.000000, 0.000000
```
