### ISSUE TITLE
Are magnetic fields automatically synchronised with electric fields in the function get_dft_array?

### ISSUE THREAD

**Issue by tmteryz** [NanoComp/meep#2508] opened 2023-05-08 06:33 UTC
hello, dear meep developers
I have noted the example（see the following picture and codes）in [meep-document](https://meep.readthedocs.io/en/latest/Python_User_Interface/#array-metadata).
so I want to confirm my understanding that magnetic fields are always automatically synchronised with electric fields in the function _get_dft_array_.  That is, the samples of the magnetic field at the moment t=nΔt is used for the discrete Fourier transform in _get_dft_array_.

![image](https://user-images.githubusercontent.com/124122684/236749643-7ff53b56-a341-4db3-ac86-6efe2388d1dd.png)

```
  # x-directed Poynting flux through monitor from frequency-domain fields
  monitor        = mp.FluxRegion(center=mon_center, size=mon_size)
  dft_cell       = sim.add_flux(freq, 0, 1, monitor)
  sim.run(...)    # timestep until DFTs converged
  (Ey,Ez,Hy,Hz)  = [sim.get_dft_array(dft_cell,c,0) for c in [mp.Ey, mp.Ez, mp.Hy, mp.Hz]]
  (x,y,z,w)      = sim.get_array_metadata(dft=dft_cell)
  flux_density   = np.real( np.conj(Ey)*Hz - np.conj(Ez)*Hy )    # array
  flux           = np.sum(w*flux_density)                        # scalar
```

**Comment by smartalecH** [comment] 2023-05-08 20:14
Duplicate of #2506.

**Closed** 2023-05-08 20:14 UTC
