### ISSUE TITLE
get_array_metadata not working when k_point is set

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#667] opened 2019-01-12 02:59 UTC
The [`get_array`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#array-slices) routine does not seem to be working properly when `k_point` is used. This is demonstrated in the following example of a 2d cell consisting of a 1d lattice of slanted blocks. A side-by-side comparison of the dielectric profile obtained using `get_epsilon`  is generated for two cases: with a `k_point` of `mp.Vector3(0,0,0)` (periodic boundaries) and without.

```py
import meep as mp
import numpy as np
import math
import matplotlib.pyplot as plt

resolution = 50

cell_size = mp.Vector3(5,2,0)

k_point = mp.Vector3(0,0,0)

rot_angle = 30

geometry = []
for j in range(5):
    geometry.append(mp.Block(material=mp.Medium(index=1.5),
                             center=mp.Vector3(-2+j,0,0),
                             size=mp.Vector3(0.5,3,0),
                             e1 = mp.Vector3(1,0,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle)),
                             e2 = mp.Vector3(0,1,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle))))

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    k_point=k_point,
                    geometry=geometry,
                    ensure_periodicity=False)
sim.init_sim()
eps = sim.get_epsilon()
(x,y,z,w) = sim.get_array_metadata()

plt.figure(dpi=150)

plt.subplot(1,2,1)
plt.pcolormesh(x,y,np.transpose(eps), shading='gouraud')
plt.axis([-2.5, 2.5, -1, 1])
plt.xlabel("x")
plt.xticks([t for t in np.arange(-2.5,3.5,1.0)])
plt.ylabel("y")
plt.yticks([t for t in np.arange(-1.0,1.5,0.5)])
plt.title("with k_point")

sim.reset_meep()

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    geometry=geometry,
                    ensure_periodicity=False)
sim.init_sim()
eps = sim.get_epsilon()
(x,y,z,w) = sim.get_array_metadata()

plt.subplot(1,2,2)
plt.pcolormesh(x,y,np.transpose(eps), shading='gouraud')
plt.axis([-2.5, 2.5, -1, 1])
plt.xlabel("x")
plt.xticks([t for t in np.arange(-2.5,3.5,1.0)])
plt.ylabel("y")
plt.yticks([t for t in np.arange(-1.0,1.5,0.5)])
plt.title("without k_point")

plt.tight_layout()
plt.show()
```
The dielectric profile is expected to be identical but is not.

![eps](https://user-images.githubusercontent.com/7152530/51068414-8f1f0100-15d2-11e9-9484-be4d34be89a4.png)

**Comment by HomerReid** [comment] 2019-02-19 19:49
I think the outcome you are looking for will probably be produced by running ```plt.pcolormesh(x,y,np.transpose(np.abs(eps)), shading='gouraud')```

**Comment by stevengj** [comment] 2019-03-08 16:01
Doing `plt.pcolormesh(np.transpose(eps), shading='gouraud')`, i.e. omitting `x` and `y`, seems to fix the problem, so apparently the problem is with `get_array_metadata`?

**Comment by stevengj** [comment] 2019-03-08 16:05
It looks fine if I do a single plot:
```
import meep as mp
import numpy as np
import math
import matplotlib.pyplot as plt

resolution = 50

cell_size = mp.Vector3(5,2,0)

k_point = mp.Vector3(0,0,0)

rot_angle = 30

geometry = []
for j in range(5):
    geometry.append(mp.Block(material=mp.Medium(index=1.5),
                             center=mp.Vector3(-2+j,0,0),
                             size=mp.Vector3(0.5,3,0),
                             e1 = mp.Vector3(1,0,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle)),
                             e2 = mp.Vector3(0,1,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle))))


sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    geometry=geometry,
                    ensure_periodicity=False)
sim.init_sim()
eps2 = sim.get_epsilon()
(x2,y2,z2,w2) = sim.get_array_metadata()

plt.pcolormesh(y2,x2,eps2)
plt.show()
```

**Comment by stevengj** [comment] 2019-03-08 16:15
It looks like the final data point in the `(x,y)` arrays for the periodic case is `(0,0)` — some kind of wraparound effect?   This is completely confusing `pcolormesh`.

This should be fixed — the `x,y` coordinates in `get_array_metadata` should not wrap around periodic cells (even if the `get_array` volume extends outside the unit cell).

**Closed** 2019-04-17 17:05 UTC
Labels: bug
