### ISSUE TITLE
use Meep functions in qt program (compile Meep to windows)

### ISSUE THREAD

**Issue by dvajdual** [NanoComp/meep#516] opened 2018-09-18 23:06 UTC
Hi guys! I want use the Meep library in qt program. Also want compile it to windows. I can't find any info how do it. Only suggestion to use Ubuntu terminal in windows (but it isn't my case...). Are there any manuals how do it? Or can you explain this? Can I compile only part of Meep functions in windows? (maybe it will be easier)

**Comment by stevengj** [comment] 2020-01-03 03:33
Duplicate of #385

**Closed by stevengj** 2020-01-03 03:33 UTC
