### ISSUE TITLE
multiple grids support?

### ISSUE THREAD

**Issue by MarkMa1990** [NanoComp/meep#2606] opened 2023-08-14 13:44 UTC
Will meep in the future has a roadmap to include multiple mesh grids as Lumerical do?

The beneficial is that it can greatly reduce the computational time when only fine precision of meshes are applied within high refractive material and boundaries.

**Comment by stevengj** [comment] 2023-08-15 14:58
Duplicate of #1442.   It's something we've thought about, but no one is working on it at the moment

**Closed by stevengj** 2023-08-15 14:58 UTC
