### ISSUE TITLE
get_array_metadata crashes for 3D simulation

### ISSUE THREAD

**Issue by klein-j** [NanoComp/meep#943] opened 2019-07-02 09:54 UTC
On meep 1.10.0-14-g5b2f4b9e, get_array_metadata crashes for 3d simulations, but not for 2d simulations:

```
import meep as mp
from meep import Vector3

print(mp.__version__)

mpSim = mp.Simulation(
	cell_size=Vector3(1, 1, 1),
	resolution=10,
)
mpSim.init_sim()
mpSim.get_array_metadata()
```

prints:
```
Using MPI version 3.1, 1 processes
1.10.0-14-g5b2f4b9e
-----------
Initializing structure...
Working in 3D dimensions.
Computational cell is 4 x 4 x 1 with resolution 20
time for set_epsilon = 0.48629 s
-----------
meep: weird yee shift for component none
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

Process finished with exit code 1
```

If I change cell_size to `Vector3(1,1,0)`, meep uses a 2D simulation and the crash does not occur. From what I can tell, get_array_metadata works for all 2D scenes and fails for all 3D scenes.

**Comment by klein-j** [comment] 2019-07-02 10:19
I tested older versions of meep, the bug seems to be introduced lately.

I installed 1.9: `conda create -n mp1.9 -c conda-forge pymeep=1.9.0 `. Interestingly, the `mp.__version__` line still prints `1.8.0-59-gd872b62`, but `conda list` shows it as meep 1.9. Anyway, the behavior is the same. 2D works, 3D does not.

For version 1.8 (which shows as `1.7.0-72-g3ea596a`), `get_array_metadata` does not crash but returns reasonably looking data for 3D scenes. So I suspect the bug to have appeared between 1.8 and 1.9.

**Comment by stevengj** [comment] 2020-02-11 19:08
Aren't you supposed to pass arguments to `get_array_metadata`?

@smartalecH mentioned another issue #881.

**Comment by stevengj** [comment] 2020-02-11 19:19
Duplicate of #881

**Closed by stevengj** 2020-02-11 19:19 UTC

**Comment by smartalecH** [comment] 2020-02-11 19:34
Now runs as is with  4f39423.
