### ISSUE TITLE
Eigenmode overlaps from `get_eigenmode_coefficients()` vary with k-direction

### ISSUE THREAD

**Issue by ianwilliamson** [NanoComp/meep#1773] opened 2021-09-29 18:35 UTC
When using `get_eigenmode_coefficients()` with `direction=mp.NO_DIRECTION` and manually specifying the direction via `kpoint_func`, the returned mode overlap values change when flipping the sign of the k-point. I believe this relates to what was observed in #1593, because the solution there was to change the k-point sign based on the direction of the requested mode overlap. 

Consider the following simulation setup:
```
frequencies = [0.45, 0.5, 0.55]
wg = mp.Block(
    center=mp.Vector3(0, 0, 0),
    material=mp.Medium(index=3.4),
    size=mp.Vector3(10, 0.5, 0),
)
source = mp.EigenModeSource(
    mp.GaussianSource(frequency=onp.mean(frequencies), fwidth=0.2),
    eig_band=1,
    direction=mp.NO_DIRECTION,
    eig_kpoint=mp.Vector3(x=1),
    size=mp.Vector3(0, 1),
    center=mp.Vector3(),
)
simulation = mp.Simulation(
    cell_size=mp.Vector3(3., 3.),
    boundary_layers=[mp.PML(1.)],
    geometry=[wg],
    sources=[source],
    resolution=20,
)
dft_mon = simulation.add_dft_fields(
    [mp.Ez],
    frequencies,
    where=mp.Volume(size=simulation.cell_size),
)
mon1 = simulation.add_mode_monitor(
    frequencies,
    mp.ModeRegion(center=mp.Vector3(+0.4), size=mp.Vector3(0, 1)),
    yee_grid=True,
)
simulation.run(until=500)
simulation.plot2D()
```
![image](https://user-images.githubusercontent.com/8869582/135327165-63096843-1523-41c6-94ff-fde0c8c25c25.png)

This produces the following DFT fields:
![image](https://user-images.githubusercontent.com/8869582/135327206-ae82f718-11a9-4b2f-9cb9-1a110b900a01.png)

The output of (automatic direction):
```
data = simulation.get_eigenmode_coefficients(
    mon1,
    [1],
    direction=mp.AUTOMATIC,
)
print(onp.abs(data.alpha))
```
is:
```
[[[1.33664502 0.00561725]
  [5.14267297 0.02121229]
  [1.65917472 0.00646342]]]
```

The output of (no direction with positive k-point):
```
data = simulation.get_eigenmode_coefficients(
    mon1,
    [1],
    direction=mp.NO_DIRECTION,
    kpoint_func=lambda *not_used: mp.Vector3(1,0,0),
)
print(onp.abs(data.alpha))
```
is:
```
[[[1.33664502 0.00561726]
  [5.14267296 0.02121239]
  [1.65917471 0.00646343]]]
```

The output of (no direction with negative k-point):
```
data = simulation.get_eigenmode_coefficients(
    mon1,
    [1],
    direction=mp.NO_DIRECTION,
    kpoint_func=lambda *not_used: mp.Vector3(-1,0,0),
)
print(onp.abs(data.alpha)
```
is:
```
[[[0.0535472  1.27748126]
  [0.26983257 4.85162955]
  [0.11030892 1.54240248]]]
```

So, the automatic direction and the positive k-point coefficient values are consistent but the negative k-point coefficient values are slightly different. I would have thought that the negative k-point coefficient values are the same, but with the fwd / bkwd array indexes swapped.

**Comment by ianwilliamson** [comment] 2021-10-04 16:44
Is what I am seeing in the results above expected or does it appear to be a bug? If it is not a bug, which mode overlap values are considered to be correct?

**Comment by oskooi** [comment] 2021-10-09 22:48
I think I have tracked down what could be the cause of the unexpected results reported here (i.e., why the mode coefficients of the backward mode are not identical to those of the forward mode with the order just swapped). It has to do with the *phase* of the eigenmodes returned by MPB via `get_eigenmode` which varies with the sign of the user-specified input parameter `kpoint`:

https://github.com/NanoComp/meep/blob/d12e544a431a1838f44f2a0f18803af470394b4f/src/mpb.cpp#L912-L916

For the 2d example posted above, I plotted the eigenmode profile for the *H<sub>y</sub>* and *E<sub>z</sub>* fields computed by MPB at the DFT line monitor and discovered that while the *H<sub>y</sub>* field is identical for the forward (`kpoint = (+1,0,0)`) and backward (`kpoint = (-1,0,0)`) modes, *E<sub>z</sub>* for the backward mode is **180° out of phase** relative to the forward mode (i.e., there is a sign flip of -1). This phase shift for a single field component is why the resulting overlap integral and thus the mode coefficients are different for the forward and backward modes.

The fix therefore involves ensuring that an identical eigenmode profile is used to compute the mode coefficients for the forward and backward modes.

**Comment by stevengj** [comment] 2021-10-13 01:54
That's correct — for the backward mode, you have to flip the relative phase of Hy and Ez

**Comment by oskooi** [comment] 2021-10-14 03:32
For some reason, when plotting the mode profile of the actual eigenmode from MPB interpolated into the Meep grid and used to compute the overlap integral from this line:

https://github.com/NanoComp/meep/blob/434f3fbf0ffe2334ce99cf105c6ec94ed44c95b7/src/dft.cpp#L945

The *E<sub>z</sub>* field is complex but *H<sub>y</sub>* is purely real as shown in the following figures for the real and imaginary parts of each field component separately. This should not affect the results but it is unexpected.

![eigmode_real_ez](https://user-images.githubusercontent.com/7152530/137246138-6e1953a3-a4a7-4c98-82a0-d7203e986f69.png)

![eigmode_imag_ez](https://user-images.githubusercontent.com/7152530/137246153-d9ab0a9d-58de-4be2-865f-7774452f620f.png)

![eigmode_real_hy](https://user-images.githubusercontent.com/7152530/137246167-b62be814-7c6b-4392-b32d-6252029a9ed1.png)

![eigmode_imag_hy](https://user-images.githubusercontent.com/7152530/137246173-3add65b0-4fbe-442f-b892-12cc04d39ffa.png)

Note: the *E<sub>z</sub>* fields of the "forward" (`kpoint=(+1,0,0)`) and "backward" (`kpoint=(-1,0,0)`) modes have a sign flip which is expected because the Poynting flux is in opposite directions.

**Comment by oskooi** [comment] 2021-10-20 00:59
It seems there is a bug when computing the mode coefficients which involve adding two different cross products `conj[E(meep)] x H(mpb)` and `conj[E(mpb)] x H(meep)` on these lines:  

https://github.com/NanoComp/meep/blob/849bf3d3ad88aae0e38a48a9cd7454987db86c66/src/mpb.cpp#L945-L946

The problem is that  `E(meep)` and `H(meep)` are located at different Yee grid points and therefore the cross products must each be computed at the *same* centered grid point before they can be added/subtracted together in the sum/difference.

**Comment by oskooi** [comment] 2021-11-01 19:37
For accurate computations of the S-parameters, note that you can always do a separate normalization run to compute the incident DFT fields from just the sources and then subtract these from the DFT fields of the "real" run. This approach is described in Section 4.3 "Separating Incident and Scattered Fields" of our book chapter: https://arxiv.org/pdf/1301.5366.pdf.

**Comment by oskooi** [comment] 2021-11-04 02:48
The *relative* difference in |S<sub>21</sub>|<sup>2</sup> and |S<sub>11</sub>|<sup>2</sup> for +k and -k is actually very similar which is reassuring. This is shown in the following figures. In the figure [above](https://user-images.githubusercontent.com/7152530/138396603-99bfb880-83e0-4d47-b294-68d71ef2600b.png), the seemingly large difference in  |S<sub>21</sub>|<sup>2</sup> relative to |S<sub>11</sub>|<sup>2</sup> is actually just an artifact of the different magnitudes: in the limit of infinite resolution, |S<sub>21</sub>|<sup>2</sup> is ~1100 whereas |S<sub>11</sub>|<sup>2</sup>  is  0 (1e-4); a difference of about 7 orders. The choice of the loglog axes obscures the difference in magnitude. For this geometry, the relative difference in +k vs. -k  (second figure below) is less than 1% at the smallest resolutions. Nevertheless, the relative difference seems to be geometry dependent and just happens to be small in this case.

![centered_grid_S11_S21](https://user-images.githubusercontent.com/7152530/140248732-a652a1b9-81d9-4fff-a62c-028ec7ad2951.png)

![centered_grid_S11_S21_relerr](https://user-images.githubusercontent.com/7152530/140248749-23ec0008-ec5b-4d72-957e-d66d6898acb5.png)

**Comment by oskooi** [comment] 2021-12-22 18:30
Closing this issue as it is not a bug but rather a feature of computing mode coefficients on the Yee grid vs. centered grid for `add_mode_monitor`.

**Closed by oskooi** 2021-12-22 18:30 UTC
