### ISSUE TITLE
Incomplete simulation results!

### ISSUE THREAD

**Issue by devrra** [NanoComp/meep#1119] opened 2020-02-08 20:01 UTC
I am new to meep. I face two problems.

1. On executing the code given on [https://github.com/NanoComp/meep/blob/master/scheme/examples/straight-waveguide.ctl](url), _straightWG-ez-000200.00.h5_ is not formed.
`yash@yash-Inspiron-5567:~/temp$ meep straightWG.ctl >& a.out`
`yash@yash-Inspiron-5567:~/temp$ ls`
`a.out  straightWG.ctl  straightWG-eps-000000.00.h5`
errors shown in _a.out_ are
`ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 564ef314ae60>`
`ERROR: In procedure %run-finalizers:`
`ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 564ef314aa80>`

2.  On executing the code given on [https://github.com/NanoComp/meep/blob/master/scheme/examples/bent-waveguide.ctl](url) I get incomplete results.
`yash@yash-Inspiron-5567:~/temp$ meep 90WG.ctl >& a.out`
`yash@yash-Inspiron-5567:~/temp$ ls`
`90WG.ctl  90WG-eps-000000.00.h5  90WG-ez.h5  a.out`
`yash@yash-Inspiron-5567:~/temp$ h5ls 90WG-ez.h5`
`ez                       Dataset {160, 160, 13/Inf}`
`yash@yash-Inspiron-5567:~/temp$ meep 90WG.ctl >& a.out`
`yash@yash-Inspiron-5567:~/temp$ h5ls 90WG-ez.h5`
`ez                       Dataset {160, 160, 18/Inf}`
around only 13 to 20 time steps are calculated. Ideally 333 time steps should have been calculated.
errors shownin _a.out_ are:
`ERROR: In procedure %run-finalizers:`
`ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 561534af3d00>`

In both the cases I ran the control files without any changes to the scripts. 
I have attached screenshot containing some system informations. If more information is needed, I will be happy to provide. Thank you in advance.
![Screenshot from 2020-02-09 01-25-20](https://user-images.githubusercontent.com/36835879/74091239-573b0380-4adb-11ea-8a14-aa7a1e1a58f4.png)

**Comment by stevengj** [comment] 2020-02-08 20:24
Looks like a duplicate of #35.   You need Meep 1.6 or later to work with the latest guile version.  I'm guessing you are using an older version of Meep.

**Closed by stevengj** 2020-02-08 20:24 UTC
