### ISSUE TITLE
Near2Far field

### ISSUE THREAD

**Issue by maihoa3210** [NanoComp/meep#2291] opened 2022-10-28 14:50 UTC
Dear Meep Developers,

I followed tutorial in Meep wedsite ( [https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/?fbclid=IwAR0y3Ydknpx8b_FGGGMda4f7pb715vbnHfmHLzwU-94nblN_uotgfFFsA_Y)) and discussion #2056. I tried to obtain the far field intensity of silver sphere like figure 2 (f) to 2(h) in this paper (DOI: 10.1088/2040-8978/17/11/114011). After trying many times and fixing, right now I dont have any ideas how to adjust my code and get good result.  The code is showed below. I hope I will receive your helps. Thank alot in advance.

import matplotlib
import matplotlib.pyplot as plt
import meep as mp
import numpy as np
from meep.materials import Ag
from matplotlib import cm
import math

resolution = 50
dpml = 1

radius = 0.04       #radius
pad = 0.05      # distance from nearfield box to PML
dist_nfb = 1.5  # distance from radius to the nearfield box

fcen = 1.00
df = 0.01

dx = ( radius + dist_nfb + pad ) * 2.
dy = dx

cell_size_nodpml = mp.Vector3(dx,dy)
cell_size = mp.Vector3(dx + 2*dpml, dy + 2*dpml)

geometry = [mp.Sphere(material=Ag,
                      center=mp.Vector3(),
                      radius=radius)]

src_cmpt=mp.Ey
sources = [mp.Source(src=mp.GaussianSource(fcen,fwidth=df),
                    center=mp.Vector3(),
                    component=src_cmpt)]

sim = mp.Simulation(
    cell_size=cell_size,
    resolution=resolution,
    geometry=geometry,
    sources=sources,
    boundary_layers=[mp.PML(dpml)]
    )

sim.run(until_after_sources=100/fcen) # run for 100 periods

silver = sim.get_array(
   component=mp.Ey,
    size=cell_size_nodpml,
    center=mp.Vector3()
    )
silver = np.transpose(silver)

Ey = sim.get_array(
    component=mp.Ey,
    size=cell_size_nodpml,
    center=mp.Vector3()
    )
Ey = np.transpose(Ey)

fig, ax = plt.subplots()

ax.imshow(
    silver,
    cmap='jet'
    )

im = ax.imshow(
    np.abs(Ey),
    alpha=0.9,cmap='jet'
    )

plt.colorbar(im,label=r'$|E_z|$')

ax.set_axis_off()

fig.savefig('save_1.png',dpi=100,bbox_inches='tight')

nfb_dx = (radius + dist_nfb) * 2. # cell in nearfield-box
nfb_dy = nfb_dx

nearfield_box = sim.add_near2far(fcen, 0, 1,
        mp.Near2FarRegion(center=mp.Vector3(0,+0.5*nfb_dy), size=mp.Vector3(nfb_dx,0), weight=+1),
    mp.Near2FarRegion(center=mp.Vector3(0,-0.5*nfb_dy), size=mp.Vector3(nfb_dx,0), weight=-1),
    mp.Near2FarRegion(center=mp.Vector3(+0.5*nfb_dx,0), size=mp.Vector3(0,nfb_dy), weight=+1),
    mp.Near2FarRegion(center=mp.Vector3(-0.5*nfb_dx,0), size=mp.Vector3(0,nfb_dy), weight=-1))

flux_box = sim.add_flux(fcen, 0, 1,
    mp.FluxRegion(center=mp.Vector3(0,+0.5*nfb_dy), size=mp.Vector3(nfb_dx,0), weight=+1),
    mp.FluxRegion(center=mp.Vector3(0,-0.5*nfb_dy), size=mp.Vector3(nfb_dx,0), weight=-1),
    mp.FluxRegion(center=mp.Vector3(+0.5*nfb_dx,0), size=mp.Vector3(0,nfb_dy), weight=+1),
    mp.FluxRegion(center=mp.Vector3(-0.5*nfb_dx,0), size=mp.Vector3(0,nfb_dy), weight=-1))

sim.run(until_after_sources= mp.stop_when_dft_decayed())

near_flux = mp.get_fluxes(flux_box)[0]

r = 1000/fcen      # half side length of far-field square box OR radius of far-field circle
res_ff = 1         # resolution of far fields (points/μm)
far_flux_box = (
    + nearfield_box.flux(mp.Y, mp.Volume(center=mp.Vector3(y=r), size=mp.Vector3(2*r)), res_ff)[0]
    - nearfield_box.flux(mp.Y, mp.Volume(center=mp.Vector3(y=-r), size=mp.Vector3(2*r)), res_ff)[0]
    + nearfield_box.flux(mp.X, mp.Volume(center=mp.Vector3(r), size=mp.Vector3(y=2*r)), res_ff)[0]
    - nearfield_box.flux(mp.X, mp.Volume(center=mp.Vector3(-r), size=mp.Vector3(y=2*r)), res_ff)[0]
    )

npts = 100
angles = 2*math.pi/npts*np.arange(npts)

E = np.zeros((npts,3),dtype=np.complex128)
H = np.zeros((npts,3),dtype=np.complex128)
for n in range(npts):
    ff = sim.get_farfield(nearfield_box,
                          mp.Vector3(r*math.cos(angles[n]),
                                     r*math.sin(angles[n])))
    E[n,:] = [np.conj(ff[j]) for j in range(3)]
    H[n,:] = [ff[j+3] for j in range(3)]

Px = np.real(E[:,1]*H[:,2]-E[:,2]*H[:,1])
Py = np.real(E[:,2]*H[:,0]-E[:,0]*H[:,2])
Pr = np.sqrt(np.square(Px)+np.square(Py))

far_flux_circle = np.sum(Pr)*2*np.pi*r/len(Pr)

print("flux:, {:.6f}, {:.6f}, {:.6f}".format(near_flux,far_flux_box,far_flux_circle))

plt.figure(dpi=200)
ax = plt.subplots(subplot_kw={'projection' : 'polar'})
ax.plot(angles, Pr/np.max(Pr),"b-")
fig.savefig('far_field.png',dpi=100,bbox_inches='tight')

Ey = sim.get_array(component=mp.Ey,size=cell_size_nodpml,center=mp.Vector3())
Ey = np.transpose(Ey)

fig, ax = plt.subplots()

ax.imshow(silver, cmap='jet')

im = ax.imshow(np.abs(Ey),alpha=0.9,cmap='jet')

plt.colorbar(im,label=r'$|E|$')

ax.set_axis_off()

fig.savefig('save_end.png',dpi=100,bbox_inches='tight')
plt.close(fig)

**Comment by smartalecH** [comment] 2022-10-30 03:17
Duplicate of #2281

**Closed** 2022-10-30 03:17 UTC
