### ISSUE TITLE
make fails: swig generates errors

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/meep#80] opened 2017-08-11 06:39 UTC
Trying to install meep-1.3 on a MacBookPro running macOS Sierra.  All the dependencies and prerequisites are installed, including guile-2.0.11 and libctl.  Downloaded the meep-1.3 tarball from GitHub, extracted and ran sh autogen.sh.  Configure ran to completion, but make stopped with the following error:

swig -I../src -c++ -guile -o meep_wrap.cxx meep.i
make[2]: swig: No such file or directory

Used "find ~ -name meep.i" to search for meep.i and found it in

$HOME/install/meep-1.3/libctl/meep.i

also

$HOME/install/meep-1.3/python/meep.i

Some environment variable needs the path, but I'm not sure which one.

Need some help.

********************************************************************************************
update 12 August 2017

Tried installing SWIG from GitHub repository to see if it would help.  First I removed meep directory.  Then I cloned SWIG from Git-Hub. SWIG installed without error.  Then I cloned meep from stevengj/meep and ran sh autogen.sh.  Script ran without stopping.  Then I ran make.  Make ended with 12 errors, all of a similar message:

meep-ctl-swig.hpp:32: Error: 'dft_flux_flux' is multiply defined in the generated target language module.
../src/meep.hpp:896: Error: Previous declaration of 'dft_flux_flux'
meep-ctl-swig.hpp:33: Error: 'dft_force_force' is multiply defined in the generated target language module.
../src/meep.hpp:925: Error: Previous declaration of 'dft_force_force'
meep-ctl-swig.hpp:34: Error: 'dft_ldos_ldos' is multiply defined in the generated target language module.
../src/meep.hpp:1000: Error: Previous declaration of 'dft_ldos_ldos'
meep-ctl-swig.hpp:35: Error: 'dft_ldos_F' is multiply defined in the generated target language module.
../src/meep.hpp:1001: Error: Previous declaration of 'dft_ldos_F'
meep-ctl-swig.hpp:36: Error: 'dft_ldos_J' is multiply defined in the generated target language module.
../src/meep.hpp:1002: Error: Previous declaration of 'dft_ldos_J'
meep-ctl-swig.hpp:37: Error: 'dft_near2far_farfield' is multiply defined in the generated target language module.
../src/meep.hpp:956: Error: Previous declaration of 'dft_near2far_farfield

These errors are different from yesterday, but appear to closely resemble errors reported here, https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05173.html

***************************************************************************************
update 14 August

Got meep-1.3 installed on macOS Sierra, running on a MacBookPro.  For some reason ONLY the tarball downloaded from the meep ab initio site installs without error.  Both the git clone and the tarball on GitHub generate the errors shown on the 12 August update.  I also found that only h5utils cloned from the GitHub work correctly with h5 files generated by meep operating on a foo.ctl file (specifically h5topng).  Other installations of h5utils from home-brew or Macports result in seg faults.

**Comment by stevengj** [comment] 2017-08-13 14:25
Duplicate of #57

**Comment by JohnWeiner** [comment] 2017-08-14 14:28
#80 is not a duplicate of #57.

#57 points out that guile versions greater than guile-2.0.11 are not compatible with meep-1.3.  #80 raises another issue….even after guile-2.0.11 is installed, and all other dependencies and prerequisites are installed (at least the ones mentioned on the meep ab initio site and in “readthedocs” on the GitHub repository), I was unable to “make” meep-1.3.

#57 appears to be a problem independent of the operating system…it is true for macOS and Ubuntu.  The problems with make in #80 were encountered with macOS Sierra running on a MacBookPro.  I don’t know if they are peculiar to macOS.

The installation note in “readthedocs” for installation on macOS will result in a nonworking meep because it instructs the reader to use home-brew to download all the prerequisites including guile.  Home-brew will install the latest version of guile which is not compatible with meep.  The same comment applies to the linux/Ubuntu installation notes.

I finally did get meep installed and working with h5utils on the MacBookPro.  I will add some notes to a message in meep-discuss that may prove useful to other users.  Judging from some of the messages in the meep-discuss archive, other users have run into similar problems in the past.

**Comment by stevengj** [comment] 2023-01-05 22:24
This issue seems to be obsolete.

**Closed by stevengj** 2023-01-05 22:24 UTC
