### ISSUE TITLE
mp.output_png generates h5 files

### ISSUE THREAD

**Issue by wenzao** [NanoComp/meep#740] opened 2019-02-22 23:26 UTC
I'm following this [tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/#output-tips-and-tricks) and this code below should generate a series of png files, but instead it's generating a series of h5 files. 
```
sim.run(mp.at_every(0.6 , mp.output_png(mp.Ez, "-Zc dkbluered")), until=200)        
```

**Comment by ChristopherHogan** [comment] 2019-02-25 13:48
Did you see this error after updating the `h5utils` package as discussed in #739?

**Comment by wenzao** [comment] 2019-02-25 19:19
Yes that is correct. This happened after I updated `h5utils`. I did not try this code before the update.

**Comment by ChristopherHogan** [comment] 2019-02-25 21:11
I can't reproduce this. Are you using an IDE or running from the command line? Can you show me the output of `conda list` and `which h5topng`?

**Comment by wenzao** [comment] 2019-02-26 17:54
I'm using Jupyter Notebook. 

The files generated by the code are like this:

![image](https://user-images.githubusercontent.com/3667282/53434638-e6730800-39ab-11e9-8139-46c7dd23ea01.png)

Conda list:
```
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.3                      py_0    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gsl                       2.4                  h14c3975_4  
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
h5utils                   1.13.1          nompi_h04274fc_101    chogan
harminv                   1.4.1                         4    chogan
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
hdf5-parallel             1.10.2                        0    chogan
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libctl                    4.2.0                h14c3975_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                 h470a237_1    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.36            h84994c4_1000    conda-forge
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13                 h470a237_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                3.0.2                 py36_1002    conda-forge
matplotlib-base           3.0.2           py36h167e16e_1002    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
mpb                       1.8.0                hac648fd_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.14.5           py36h1b885b7_4  
numpy-base                1.14.5           py36hdbf6ddf_4  
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openmpi                   2.0.2                         0    conda-forge
openssl                   1.1.1a            h14c3975_1000    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.0                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.4.1           py36h00a061d_1000    conda-forge
pip                       9.0.3                    py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pymeep                    1.8.0            py36h61a843b_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      4.11.4                   py36_3    conda-forge
python                    3.6.8                h0371630_0  
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyzmq                     17.1.0           py36hae99301_0    conda-forge
qt                        4.8.7                         2  
qtconsole                 4.3.1                    py36_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
scipy                     1.1.0            py36hc49cb51_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.0.0                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1                      py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.31.1                   py36_0    conda-forge
widgetsnbextension        3.2.1                    py36_0    conda-forge
xorg-libxau               1.0.8                h470a237_5    conda-forge
xorg-libxdmcp             1.1.2                h470a237_6    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zeromq                    4.2.5                hfc679d8_3    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

And which h5topng
```
$ which h5topng
/usr/local/xxx/miniconda3/envs/mp/bin/h5topng
```

**Comment by ChristopherHogan** [comment] 2019-02-26 19:42
I was unable to reproduce the issue in a Jupyter notebook. Can you try running it from the command line instead of a notebook?

**Comment by tsehso** [comment] 2019-04-09 22:19
Hi, I also met this problem earlier, but I already solved it by using a gentleman's suggestion, which I found online.

I attached the website below so that everyone who meets the same question knows how to handle it.
https://askubuntu.com/questions/663625/how-to-convert-h5-file-to-image-h5topng-not-working

**Comment by RokVenturini** [comment] 2020-03-25 10:19
I seem to have the same issue as wenzao. After following the [tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/) and running the code
`sim.run(mp.at_every(0.6 , mp.output_png(mp.Ez, "-Zc dkbluered")), until=200)`
I get a series of hd5 files instead of pngs. I also get colormap error. I am running code on jupyter notebook inside conda mp environment and have updated h5utils with conda-forge.

It seems to be the same issue of h5utils with conda mp environment as discussed here [#1066](https://github.com/NanoComp/meep/issues/1066). I am able to create pngs from h5 files if I use h5topng from package manager outside conda mp environment, but not inside conda mp environment (colormap error). I would still like to use mp.output_png() to avoid exporting large h5 files, is there any way to do that?

**Comment by stevengj** [comment] 2020-03-29 18:34
Make sure the location of `h5topng` is included in your `PATH`

**Comment by RokVenturini** [comment] 2020-03-31 16:02
I only now realized that this issue (#740) is older than [#1066](https://github.com/NanoComp/meep/issues/1066). For now I will follow suggestion from [#1066](https://github.com/NanoComp/meep/issues/1066) to use h5topng from h5utils that was installed with package manager as that works for me.

**Comment by stevengj** [comment] 2020-04-02 19:27
Closing as a duplicate of  #1066.

**Closed by stevengj** 2020-04-02 19:27 UTC
