### ISSUE TITLE
On WSL(Ubuntu), meep don't work. python straight-waveguide.py, got error: no mudule named "meep'

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#806] opened 2019-04-08 21:26 UTC
I just installed precompiled meep package on WSL (Ubuntu) from https://meep.readthedocs.io/en/latest/Installation ,  apt-get install meep h5utils.
To test it, I run
Python straight-waveguide.py
got 👍 
Traceback (most recent call last):
  File "straight-waveguide.py", line 6, in <module>
    import meep as mp
ModuleNotFoundError: No module named 'meep'
I tried python, python2, 2.7, python 3, 3.6, 3m  etc, no one worked.
Do you know this prcompliled version is work or not?
_________________________
BTW, after install precompiled meep, in fact, all of pakckages: libct, harminv, hdf5, blas,guile ... also installed on standard dir(/usr/bin, /usr/lib,/usr/include), but configure meep source package, still got could find hdf5, could not connect to guile error. seems WSL(Ubuntu) is simpler for port meep.

Thanks for your help

**Comment by ChristopherHogan** [comment] 2019-04-08 21:30
The debian package installed via apt-get is out of date (version 1.3) and does not include the Python interface. Have you tried the conda package on WSL? That should work for you.

**Comment by stevengj** [comment] 2019-04-08 21:46
Duplicate of #803. 

Please don’t file duplicate issues, and don’t file issues every time you don’t understand something. GitHub issues are not a general help desk.

**Closed by stevengj** 2019-04-08 21:46 UTC

**Comment by genlintan** [comment] 2019-04-09 01:06
I have installed conda meep and got success, thank you for your instructions.
I run an example python straight-wave-guide.py and got success.
But WSL Ubuntu has bugs, only display a figure, 
run 0 finished at t = 200.0 (4000 timesteps)
libGL error: No matching fbConfigs or visuals found

libGL error: failed to load driver: swrast
QXcbConnection: XCB error: 3 (BadWindow), sequence: 178, resource id: 2097157, major code: 20 (GetProperty), minor code: 0

But I do not want to bother you, I know this issue is not help desk. I think them by myself.
Thank you very much, Best Wishes.

**Comment by genlintan** [comment] 2019-04-09 15:44
Mr. Hogan. Thanks for yor help. I installed conda meep and got success. Then I tried to run an example to test it; run python straight-waveguide.py got success, but only display one figure, then got error:gltan@Genlin2015-PC:~/meep-1.8.0/python/examples$ source activate mp(mp) gltan@Genlin2015-PC:~/meep-1.8.0/python/examples$ python straight-waveguide.py -----------Initializing structure...Working in 2D dimensions.Computational cell is 16 x 8 x 0 with resolution 10     block, center = (0,0,0)          size (1e+20,1,1e+20)          axes (1,0,0), (0,1,0), (0,0,1)          dielectric constant epsilon diagonal = (12,12,12)time for set_epsilon = 0.154158 s-----------run 0 finished at t = 200.0 (4000 timesteps)/home/gltan/.conda/envs/mp/lib/python3.7/site-packages/matplotlib/font_manager.py:232: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.  'Matplotlib is building the font cache using fc-list. 'libGL error: No matching fbConfigs or visuals foundlibGL error: failed to load driver: swrastQXcbConnection: XCB error: 3 (BadWindow), sequence: 178, resource id: 2097157, major code: 20 (GetProperty), minor code: 0
I think it is WSL Ubuntu's bugs. I found  many people reported  this issue online, but without solution so far.
BTW, on cygwin, meep has worked using scheme according to your instructions, Thank you very much. I still work on python issue ( This seems related to mpb problem). If you have some suggestions, let me know, Thank you very much.
Best Wishes
Genlin Tan 

    On Monday, April 8, 2019, 5:30:30 PM EDT, Christopher Hogan <notifications@github.com> wrote:  
 
 
The debian package installed via apt-get is out of date (version 1.3) and does not include the Python interface. Have you tried the conda package on WSL? That should work for you.

**Comment by ChristopherHogan** [comment] 2019-04-09 15:51
You can use `plt.save("name.png")` instead of `plt.show()`. This will save the image to your machine, and you can then view it in Windows. The other option is to run in a jupyter notebook (see the `.ipynb` files in `meep/python/examples`.

**Comment by genlintan** [comment] 2019-04-10 14:25
Dear Dr. Hogen,
 I tried change plt.show() to plt.save( "straight-waveguide_1.png"),and plt.save( "straight-waveguide_2.png") and  re-run python straight-waveguide, no error, and no figure, and program end normally. But could not find saved file straight-waveguide_1.png and straight-waveguide_2.png. I don't kown what is problem.Sorry bother you again Thank you very much for your help
Genlin Tan  

    On Tuesday, April 9, 2019, 11:51:06 AM EDT, Christopher Hogan <notifications@github.com> wrote:  
 
 
You can use plt.save("name.png") instead of plt.show(). This will save the image to your machine, and you can then view it in Windows. The other option is to run in a jupyter notebook (see the .ipynb files in meep/python/examples.

**Comment by ChristopherHogan** [comment] 2019-04-10 14:28
Sorry, it should be `plt.savefig()`. Check the [matplotlib documentation](https://matplotlib.org/contents.html) for more details.

**Comment by genlintan** [comment] 2019-04-10 14:50
Hi Dr.Hogan,
  That is great, I got two figures on win10.
  Thank you very much for your help
Genlin Tan  

    On Wednesday, April 10, 2019, 10:28:29 AM EDT, Christopher Hogan <notifications@github.com> wrote:  
 
 
Sorry, it should be plt.savefig(). Check the matplotlib documentation for more details.

**Comment by genlintan** [comment] 2019-04-26 22:34
Hi, Dr.Hogen,
 h52gif convers xx.h5 to xx.gif issue:(1) On WSL and mp, run python  bent-waveguide.py create two xxx.h5 files, I used h52gif got xxx.gif, but on win 10, use any figure software could not see any thing.
(2) On cygwin, I have scheme version of meep, run meep xx.ctl, got xx.h5 file , use h52gif to get xx.gif, could not see any thing.(3) On WSL, use precompiled meep, even got errors and could not get xx.h5 file.I am not sure this is HDF5 problem or meep (or python) problem Thank you for your help in advance
Best Regards
Genlin Tan  

    On Wednesday, April 10, 2019, 10:28:29 AM EDT, Christopher Hogan <notifications@github.com> wrote:  
 
 
Sorry, it should be plt.savefig(). Check the matplotlib documentation for more details.

**Comment by ChristopherHogan** [comment] 2019-04-29 12:48
Please read the tutorial for the [bent waveguide](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/). It uses `h52png` to create several pngs from the h5 file, then it uses ImageMagick's `convert` to turn the pngs into a gif.
